#!/usr/bin/env python3
"""
Verbatim transcription of the OFFICIAL USCIS 2025 civics test:
"128 Civics Questions and Answers (2025 version)", form M-1778 (09/25).

Source: PDF supplied directly by the user (uscis.gov blocks automated
fetch from this environment — see reports/civics_diff.md for details).
Transcribed by hand from the fetched PDF pages; every question and every
accepted answer bullet below is copied as printed, not reworded.

Self-check performed: exactly 20 questions are marked is65_20=True below,
matching the document's own stated invariant ("The USCIS officer will ask
you to answer 10 out of the 20 civics test questions with an asterisk").
"""

SECTION_TO_CATEGORY = {
    "gov_principles": "AMERICAN GOVERNMENT > A: Principles of American Government",
    "gov_system": "AMERICAN GOVERNMENT > B: System of Government",
    "gov_rights": "AMERICAN GOVERNMENT > C: Rights and Responsibilities",
    "history_colonial": "AMERICAN HISTORY > A: Colonial Period and Independence",
    "history_1800s": "AMERICAN HISTORY > B: 1800s",
    "history_recent": "AMERICAN HISTORY > C: Recent American History and Other Important Historical Information",
    "symbols": "SYMBOLS AND HOLIDAYS > A: Symbols",
    "holidays": "SYMBOLS AND HOLIDAYS > B: Holidays",
}


def q(oid, category, text, answers, star=False, count=1, note=None, dynamic=None, role=None):
    return {
        "officialId2025": oid,
        "category": category,
        "questionEN": text,
        "answersEN": answers,
        "is65_20_2025": star,
        "requiredAnswerCount": count,
        "note": note,
        "dynamicType": dynamic,
        "officeholderRole": role,
    }


OFFICIAL_2025 = [
    q(1, "gov_principles", "What is the form of government of the United States?",
      ["Republic", "Constitution-based federal republic", "Representative democracy"]),
    q(2, "gov_principles", "What is the supreme law of the land?",
      ["(U.S.) Constitution"], star=True),
    q(3, "gov_principles", "Name one thing the U.S. Constitution does.",
      ["Forms the government", "Defines powers of government", "Defines the parts of government",
       "Protects the rights of the people"]),
    q(4, "gov_principles", "The U.S. Constitution starts with the words “We the People.” What does “We the People” mean?",
      ["Self-government", "Popular sovereignty", "Consent of the governed",
       "People should govern themselves", "(Example of) social contract"]),
    q(5, "gov_principles", "How are changes made to the U.S. Constitution?",
      ["Amendments", "The amendment process"]),
    q(6, "gov_principles", "What does the Bill of Rights protect?",
      ["(The basic) rights of Americans", "(The basic) rights of people living in the United States"]),
    q(7, "gov_principles", "How many amendments does the U.S. Constitution have?",
      ["Twenty-seven (27)"], star=True),
    q(8, "gov_principles", "Why is the Declaration of Independence important?",
      ["It says America is free from British control.", "It says all people are created equal.",
       "It identifies inherent rights.", "It identifies individual freedoms."]),
    q(9, "gov_principles", "What founding document said the American colonies were free from Britain?",
      ["Declaration of Independence"]),
    q(10, "gov_principles", "Name two important ideas from the Declaration of Independence and the U.S. Constitution.",
      ["Equality", "Liberty", "Social contract", "Natural rights", "Limited government", "Self-government"], count=2),
    q(11, "gov_principles", "The words “Life, Liberty, and the pursuit of Happiness” are in what founding document?",
      ["Declaration of Independence"]),
    q(12, "gov_principles", "What is the economic system of the United States?",
      ["Capitalism", "Free market economy"], star=True),
    q(13, "gov_principles", "What is the rule of law?",
      ["Everyone must follow the law.", "Leaders must obey the law.", "Government must obey the law.",
       "No one is above the law."]),
    q(14, "gov_principles", "Many documents influenced the U.S. Constitution. Name one.",
      ["Declaration of Independence", "Articles of Confederation", "Federalist Papers", "Anti-Federalist Papers",
       "Virginia Declaration of Rights", "Fundamental Orders of Connecticut", "Mayflower Compact",
       "Iroquois Great Law of Peace"]),
    q(15, "gov_principles", "There are three branches of government. Why?",
      ["So one part does not become too powerful", "Checks and balances", "Separation of powers"]),

    q(16, "gov_system", "Name the three branches of government.",
      ["Legislative, executive, and judicial", "Congress, president, and the courts"], count=3),
    q(17, "gov_system", "The President of the United States is in charge of which branch of government?",
      ["Executive branch"]),
    q(18, "gov_system", "What part of the federal government writes laws?",
      ["(U.S.) Congress", "(U.S. or national) legislature", "Legislative branch"]),
    q(19, "gov_system", "What are the two parts of the U.S. Congress?",
      ["Senate and House (of Representatives)"], count=2),
    q(20, "gov_system", "Name one power of the U.S. Congress.",
      ["Writes laws", "Declares war", "Makes the federal budget"], star=True),
    q(21, "gov_system", "How many U.S. senators are there?",
      ["One hundred (100)"]),
    q(22, "gov_system", "How long is a term for a U.S. senator?",
      ["Six (6) years"]),
    q(23, "gov_system", "Who is one of your state’s U.S. senators now?",
      [], note="Answers will vary. [District of Columbia residents and residents of U.S. territories should answer "
               "that D.C. (or the territory where the applicant lives) has no U.S. senators.]",
      dynamic="userStateOfficeholder", role="stateSenators"),
    q(24, "gov_system", "How many voting members are in the House of Representatives?",
      ["Four hundred thirty-five (435)"]),
    q(25, "gov_system", "How long is a term for a member of the House of Representatives?",
      ["Two (2) years"]),
    q(26, "gov_system", "Why do U.S. representatives serve shorter terms than U.S. senators?",
      ["To more closely follow public opinion"]),
    q(27, "gov_system", "How many senators does each state have?",
      ["Two (2)"]),
    q(28, "gov_system", "Why does each state have two senators?",
      ["Equal representation (for small states)", "The Great Compromise (Connecticut Compromise)"]),
    q(29, "gov_system", "Name your U.S. representative.",
      [], note="Answers will vary. [Residents of territories with nonvoting Delegates or Resident Commissioners "
               "may provide the name of that Delegate or Commissioner. Also acceptable is any statement that the "
               "territory has no (voting) representatives in Congress.]",
      dynamic="userStateOfficeholder", role="representative"),
    q(30, "gov_system", "What is the name of the Speaker of the House of Representatives now?",
      [], star=True, note="Visit uscis.gov/citizenship/testupdates for the name of the Speaker of the House of Representatives.",
      dynamic="nationalOfficeholder", role="speakerOfHouse"),
    q(31, "gov_system", "Who does a U.S. senator represent?",
      ["Citizens of their state", "People of their state"]),
    q(32, "gov_system", "Who elects U.S. senators?",
      ["Citizens from their state"]),
    q(33, "gov_system", "Who does a member of the House of Representatives represent?",
      ["Citizens in their (congressional) district", "Citizens in their district",
       "People from their (congressional) district", "People in their district"]),
    q(34, "gov_system", "Who elects members of the House of Representatives?",
      ["Citizens from their (congressional) district"]),
    q(35, "gov_system", "Some states have more representatives than other states. Why?",
      ["(Because of) the state’s population", "(Because) they have more people",
       "(Because) some states have more people"]),
    q(36, "gov_system", "The President of the United States is elected for how many years?",
      ["Four (4) years"], star=True),
    q(37, "gov_system", "The President of the United States can serve only two terms. Why?",
      ["(Because of) the 22nd Amendment", "To keep the president from becoming too powerful"]),
    q(38, "gov_system", "What is the name of the President of the United States now?",
      [], star=True, note="Visit uscis.gov/citizenship/testupdates for the name of the President of the United States.",
      dynamic="nationalOfficeholder", role="president"),
    q(39, "gov_system", "What is the name of the Vice President of the United States now?",
      [], star=True, note="Visit uscis.gov/citizenship/testupdates for the name of the Vice President of the United States.",
      dynamic="nationalOfficeholder", role="vicePresident"),
    q(40, "gov_system", "If the president can no longer serve, who becomes president?",
      ["The Vice President (of the United States)"]),
    q(41, "gov_system", "Name one power of the president.",
      ["Signs bills into law", "Vetoes bills", "Enforces laws", "Commander in Chief (of the military)",
       "Chief diplomat", "Appoints federal judges"]),
    q(42, "gov_system", "Who is Commander in Chief of the U.S. military?",
      ["The President (of the United States)"]),
    q(43, "gov_system", "Who signs bills to become laws?",
      ["The President (of the United States)"]),
    q(44, "gov_system", "Who vetoes bills?",
      ["The President (of the United States)"], star=True),
    q(45, "gov_system", "Who appoints federal judges?",
      ["The President (of the United States)"]),
    q(46, "gov_system", "The executive branch has many parts. Name one.",
      ["President (of the United States)", "Cabinet", "Federal departments and agencies"]),
    q(47, "gov_system", "What does the President’s Cabinet do?",
      ["Advises the President (of the United States)"]),
    q(48, "gov_system", "What are two Cabinet-level positions?",
      ["Attorney General", "Secretary of Agriculture", "Secretary of Commerce", "Secretary of Education",
       "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security",
       "Secretary of Housing and Urban Development", "Secretary of the Interior", "Secretary of Labor",
       "Secretary of State", "Secretary of Transportation", "Secretary of the Treasury",
       "Secretary of Veterans Affairs", "Secretary of War (Defense)", "Vice-President",
       "Administrator of the Environmental Protection Agency", "Administrator of the Small Business Administration",
       "Director of the Central Intelligence Agency", "Director of the Office of Management and Budget",
       "Director of National Intelligence", "United States Trade Representative"], count=2),
    q(49, "gov_system", "Why is the Electoral College important?",
      ["It decides who is elected president.",
       "It provides a compromise between the popular election of the president and congressional selection."]),
    q(50, "gov_system", "What is one part of the judicial branch?",
      ["Supreme Court", "Federal Courts"]),
    q(51, "gov_system", "What does the judicial branch do?",
      ["Reviews laws", "Explains laws", "Resolves disputes (disagreements) about the law",
       "Decides if a law goes against the (U.S.) Constitution"]),
    q(52, "gov_system", "What is the highest court in the United States?",
      ["Supreme Court"], star=True),
    q(53, "gov_system", "How many seats are on the Supreme Court?",
      ["Nine (9)"]),
    q(54, "gov_system", "How many Supreme Court justices are usually needed to decide a case?",
      ["Five (5)"]),
    q(55, "gov_system", "How long do Supreme Court justices serve?",
      ["(For) life", "Lifetime appointment", "(Until) retirement"]),
    q(56, "gov_system", "Supreme Court justices serve for life. Why?",
      ["To be independent (of politics)", "To limit outside (political) influence"]),
    q(57, "gov_system", "Who is the Chief Justice of the United States now?",
      [], note="Visit uscis.gov/citizenship/testupdates for the name of the Chief Justice of the United States.",
      dynamic="nationalOfficeholder", role="chiefJustice"),
    q(58, "gov_system", "Name one power that is only for the federal government.",
      ["Print paper money", "Mint coins", "Declare war", "Create an army", "Make treaties", "Set foreign policy"]),
    q(59, "gov_system", "Name one power that is only for the states.",
      ["Provide schooling and education", "Provide protection (police)", "Provide safety (fire departments)",
       "Give a driver’s license", "Approve zoning and land use"]),
    q(60, "gov_system", "What is the purpose of the 10th Amendment?",
      ["(It states that the) powers not given to the federal government belong to the states or to the people."]),
    q(61, "gov_system", "Who is the governor of your state now?",
      [], star=True, note="Answers will vary. [District of Columbia residents should answer that D.C. does not have a governor.]",
      dynamic="userStateOfficeholder", role="governor"),
    q(62, "gov_system", "What is the capital of your state?",
      [], note="Answers will vary. [District of Columbia residents should answer that D.C. is not a state and does "
               "not have a capital. Residents of U.S. territories should name the capital of the territory.]",
      dynamic="userStateCapital"),

    q(63, "gov_rights", "There are four amendments to the U.S. Constitution about who can vote. Describe one of them.",
      ["Citizens eighteen (18) and older (can vote).", "You don’t have to pay (a poll tax) to vote.",
       "Any citizen can vote. (Women and men can vote.)", "A male citizen of any race (can vote)."]),
    q(64, "gov_rights", "Who can vote in federal elections, run for federal office, and serve on a jury in the United States?",
      ["Citizens", "Citizens of the United States", "U.S. citizens"]),
    q(65, "gov_rights", "What are three rights of everyone living in the United States?",
      ["Freedom of expression", "Freedom of speech", "Freedom of assembly", "Freedom to petition the government",
       "Freedom of religion", "The right to bear arms"], count=3),
    q(66, "gov_rights", "What do we show loyalty to when we say the Pledge of Allegiance?",
      ["The United States", "The flag"], star=True),
    q(67, "gov_rights", "Name two promises that new citizens make in the Oath of Allegiance.",
      ["Give up loyalty to other countries", "Defend the (U.S.) Constitution", "Obey the laws of the United States",
       "Serve in the military (if needed)", "Serve (help, do important work for) the nation (if needed)",
       "Be loyal to the United States"], count=2),
    q(68, "gov_rights", "How can people become United States citizens?",
      ["Be born in the United States, under the conditions set by the 14th Amendment", "Naturalize",
       "Derive citizenship (under conditions set by Congress)"]),
    q(69, "gov_rights", "What are two examples of civic participation in the United States?",
      ["Vote", "Run for office", "Join a political party", "Help with a campaign", "Join a civic group",
       "Join a community group", "Give an elected official your opinion (on an issue)", "Contact elected officials",
       "Support or oppose an issue or policy", "Write to a newspaper"], count=2),
    q(70, "gov_rights", "What is one way Americans can serve their country?",
      ["Vote", "Pay taxes", "Obey the law", "Serve in the military", "Run for office",
       "Work for local, state, or federal government"]),
    q(71, "gov_rights", "Why is it important to pay federal taxes?",
      ["Required by law", "All people pay to fund the federal government",
       "Required by the (U.S.) Constitution (16th Amendment)", "Civic duty"]),
    q(72, "gov_rights", "It is important for all men age 18 through 25 to register for the Selective Service. Name one reason why.",
      ["Required by law", "Civic duty", "Makes the draft fair, if needed"]),

    q(73, "history_colonial", "The colonists came to America for many reasons. Name one.",
      ["Freedom", "Political liberty", "Religious freedom", "Economic opportunity", "Escape persecution"]),
    q(74, "history_colonial", "Who lived in America before the Europeans arrived?",
      ["American Indians", "Native Americans"], star=True),
    q(75, "history_colonial", "What group of people was taken and sold as slaves?",
      ["Africans", "People from Africa"]),
    q(76, "history_colonial", "What war did the Americans fight to win independence from Britain?",
      ["American Revolution", "The (American) Revolutionary War", "War for (American) Independence"]),
    q(77, "history_colonial", "Name one reason why the Americans declared independence from Britain.",
      ["High taxes", "Taxation without representation",
       "British soldiers stayed in Americans’ houses (boarding, quartering)", "They did not have self-government",
       "Boston Massacre", "Boston Tea Party (Tea Act)", "Stamp Act", "Sugar Act", "Townshend Acts",
       "Intolerable (Coercive) Acts"]),
    q(78, "history_colonial", "Who wrote the Declaration of Independence?",
      ["(Thomas) Jefferson"], star=True),
    q(79, "history_colonial", "When was the Declaration of Independence adopted?",
      ["July 4, 1776"]),
    q(80, "history_colonial", "The American Revolution had many important events. Name one.",
      ["(Battle of) Bunker Hill", "Declaration of Independence", "Washington Crossing the Delaware (Battle of Trenton)",
       "(Battle of) Saratoga", "Valley Forge (Encampment)", "(Battle of) Yorktown (British surrender at Yorktown)"]),
    q(81, "history_colonial", "There were 13 original states. Name five.",
      ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania",
       "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"], count=5),
    q(82, "history_colonial", "What founding document was written in 1787?",
      ["(U.S.) Constitution"]),
    q(83, "history_colonial", "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
      ["(James) Madison", "(Alexander) Hamilton", "(John) Jay", "Publius"]),
    q(84, "history_colonial", "Why were the Federalist Papers important?",
      ["They helped people understand the (U.S.) Constitution.", "They supported passing the (U.S.) Constitution."]),
    q(85, "history_colonial", "Benjamin Franklin is famous for many things. Name one.",
      ["Founded the first free public libraries", "First Postmaster General of the United States",
       "Helped write the Declaration of Independence", "Inventor", "U.S. diplomat"]),
    q(86, "history_colonial", "George Washington is famous for many things. Name one.",
      ["“Father of Our Country”", "First president of the United States",
       "General of the Continental Army", "President of the Constitutional Convention"], star=True),
    q(87, "history_colonial", "Thomas Jefferson is famous for many things. Name one.",
      ["Writer of the Declaration of Independence", "Third president of the United States",
       "Doubled the size of the United States (Louisiana Purchase)", "First Secretary of State",
       "Founded the University of Virginia", "Writer of the Virginia Statute on Religious Freedom"]),
    q(88, "history_colonial", "James Madison is famous for many things. Name one.",
      ["“Father of the Constitution”", "Fourth president of the United States",
       "President during the War of 1812", "One of the writers of the Federalist Papers"]),
    q(89, "history_colonial", "Alexander Hamilton is famous for many things. Name one.",
      ["First Secretary of the Treasury", "One of the writers of the Federalist Papers",
       "Helped establish the First Bank of the United States", "Aide to General George Washington",
       "Member of the Continental Congress"]),

    q(90, "history_1800s", "What territory did the United States buy from France in 1803?",
      ["Louisiana Territory", "Louisiana"]),
    q(91, "history_1800s", "Name one war fought by the United States in the 1800s.",
      ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"]),
    q(92, "history_1800s", "Name the U.S. war between the North and the South.",
      ["The Civil War"]),
    q(93, "history_1800s", "The Civil War had many important events. Name one.",
      ["(Battle of) Fort Sumter", "Emancipation Proclamation", "(Battle of) Vicksburg", "(Battle of) Gettysburg",
       "Sherman’s March", "(Surrender at) Appomattox", "(Battle of) Antietam/Sharpsburg",
       "Lincoln was assassinated."]),
    q(94, "history_1800s", "Abraham Lincoln is famous for many things. Name one.",
      ["Freed the slaves (Emancipation Proclamation)", "Saved (or preserved) the Union",
       "Led the United States during the Civil War", "16th president of the United States",
       "Delivered the Gettysburg Address"], star=True),
    q(95, "history_1800s", "What did the Emancipation Proclamation do?",
      ["Freed the slaves", "Freed slaves in the Confederacy", "Freed slaves in the Confederate states",
       "Freed slaves in most Southern states"]),
    q(96, "history_1800s", "What U.S. war ended slavery?",
      ["The Civil War"]),
    q(97, "history_1800s", "What amendment says all persons born or naturalized in the United States, and subject to "
                           "the jurisdiction thereof, are U.S. citizens?",
      ["14th Amendment"]),
    q(98, "history_1800s", "When did all men get the right to vote?",
      ["After the Civil War", "During Reconstruction", "(With the) 15th Amendment", "1870"]),
    q(99, "history_1800s", "Name one leader of the women’s rights movement in the 1800s.",
      ["Susan B. Anthony", "Elizabeth Cady Stanton", "Sojourner Truth", "Harriet Tubman", "Lucretia Mott",
       "Lucy Stone"]),

    q(100, "history_recent", "Name one war fought by the United States in the 1900s.",
      ["World War I", "World War II", "Korean War", "Vietnam War", "(Persian) Gulf War"]),
    q(101, "history_recent", "Why did the United States enter World War I?",
      ["Because Germany attacked U.S. (civilian) ships", "To support the Allied Powers (England, France, Italy, and Russia)",
       "To oppose the Central Powers (Germany, Austria-Hungary, the Ottoman Empire, and Bulgaria)"]),
    q(102, "history_recent", "When did all women get the right to vote?",
      ["1920", "After World War I", "(With the) 19th Amendment"]),
    q(103, "history_recent", "What was the Great Depression?",
      ["Longest economic recession in modern history"]),
    q(104, "history_recent", "When did the Great Depression start?",
      ["The Great Crash (1929)", "Stock market crash of 1929"]),
    q(105, "history_recent", "Who was president during the Great Depression and World War II?",
      ["(Franklin) Roosevelt"]),
    q(106, "history_recent", "Why did the United States enter World War II?",
      ["(Bombing of) Pearl Harbor", "Japanese attacked Pearl Harbor",
       "To support the Allied Powers (England, France, and Russia)", "To oppose the Axis Powers (Germany, Italy, and Japan)"]),
    q(107, "history_recent", "Dwight Eisenhower is famous for many things. Name one.",
      ["General during World War II", "President at the end of (during) the Korean War",
       "34th president of the United States", "Signed the Federal-Aid Highway Act of 1956 (Created the Interstate System)"]),
    q(108, "history_recent", "Who was the United States’ main rival during the Cold War?",
      ["Soviet Union", "USSR", "Russia"]),
    q(109, "history_recent", "During the Cold War, what was one main concern of the United States?",
      ["Communism", "Nuclear war"]),
    q(110, "history_recent", "Why did the United States enter the Korean War?",
      ["To stop the spread of communism"]),
    q(111, "history_recent", "Why did the United States enter the Vietnam War?",
      ["To stop the spread of communism"]),
    q(112, "history_recent", "What did the civil rights movement do?",
      ["Fought to end racial discrimination"]),
    q(113, "history_recent", "Martin Luther King, Jr. is famous for many things. Name one.",
      ["Fought for civil rights", "Worked for equality for all Americans",
       "Worked to ensure that people would “not be judged by the color of their skin, but by the content of their character”"],
      star=True),
    q(114, "history_recent", "Why did the United States enter the Persian Gulf War?",
      ["To force the Iraqi military from Kuwait"]),
    q(115, "history_recent", "What major event happened on September 11, 2001 in the United States?",
      ["Terrorists attacked the United States",
       "Terrorists took over two planes and crashed them into the World Trade Center in New York City",
       "Terrorists took over a plane and crashed into the Pentagon in Arlington, Virginia",
       "Terrorists took over a plane originally aimed at Washington, D.C., and crashed in a field in Pennsylvania"],
      star=True),
    q(116, "history_recent", "Name one U.S. military conflict after the September 11, 2001 attacks.",
      ["(Global) War on Terror", "War in Afghanistan", "War in Iraq"]),
    q(117, "history_recent", "Name one American Indian tribe in the United States.",
      ["Apache", "Blackfeet", "Cayuga", "Cherokee", "Cheyenne", "Chippewa", "Choctaw", "Creek", "Crow", "Hopi",
       "Huron", "Inupiat", "Lakota", "Mohawk", "Mohegan", "Navajo", "Oneida", "Onondaga", "Pueblo", "Seminole",
       "Seneca", "Shawnee", "Sioux", "Teton", "Tuscarora"],
      note="For a complete list of tribes, please visit bia.gov."),
    q(118, "history_recent", "Name one example of an American innovation.",
      ["Light bulb", "Automobile (cars, internal combustion engine)", "Skyscrapers", "Airplane", "Assembly line",
       "Landing on the moon", "Integrated circuit (IC)"]),

    q(119, "symbols", "What is the capital of the United States?",
      ["Washington, D.C."]),
    q(120, "symbols", "Where is the Statue of Liberty?",
      ["New York (Harbor)", "Liberty Island"],
      note="Also acceptable are New Jersey, near New York City, and on the Hudson (River)."),
    q(121, "symbols", "Why does the flag have 13 stripes?",
      ["(Because there were) 13 original colonies", "(Because the stripes) represent the original colonies"], star=True),
    q(122, "symbols", "Why does the flag have 50 stars?",
      ["(Because there is) one star for each state", "(Because) each star represents a state",
       "(Because there are) 50 states"]),
    q(123, "symbols", "What is the name of the national anthem?",
      ["The Star-Spangled Banner"]),
    q(124, "symbols", "The Nation’s first motto was “E Pluribus Unum.” What does that mean?",
      ["Out of many, one", "We all become one"]),

    q(125, "holidays", "What is Independence Day?",
      ["A holiday to celebrate U.S. independence (from Britain)", "The country’s birthday"]),
    q(126, "holidays", "Name three national U.S. holidays.",
      ["New Year’s Day", "Martin Luther King, Jr. Day", "Presidents Day (Washington’s Birthday)",
       "Memorial Day", "Juneteenth", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day",
       "Thanksgiving Day", "Christmas Day"], star=True, count=3),
    q(127, "holidays", "What is Memorial Day?",
      ["A holiday to honor soldiers who died in military service"]),
    q(128, "holidays", "What is Veterans Day?",
      ["A holiday to honor people in the (U.S.) military", "A holiday to honor people who have served (in the U.S. military)"]),
]

if __name__ == "__main__":
    import json
    import os

    assert len(OFFICIAL_2025) == 128, f"expected 128, got {len(OFFICIAL_2025)}"
    ids = sorted(item["officialId2025"] for item in OFFICIAL_2025)
    assert ids == list(range(1, 129)), "officialId2025 must be exactly 1..128"
    starred = [item["officialId2025"] for item in OFFICIAL_2025 if item["is65_20_2025"]]
    assert len(starred) == 20, f"expected exactly 20 starred (65/20) questions, got {len(starred)}: {starred}"

    out_path = os.path.join(os.path.dirname(__file__), "official_2025_civics.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(OFFICIAL_2025, f, ensure_ascii=False, indent=2)
    print(f"wrote {out_path}: {len(OFFICIAL_2025)} questions, {len(starred)} starred (65/20)")
    print(f"starred ids: {starred}")
