import FirebaseFirestore
import Foundation

/// Mirrors `videos/{videoId}` — top-level, not a subcollection of `topics`,
/// because the feed queries across topics. `r2Key` deliberately isn't
/// modeled here: the client only ever needs `playbackURL`.
///
/// A video is only servable to a learner when `status == .ready`,
/// `visibility == .public`, `topicVisibility == .public`, and
/// `isDeleted == false` — see `videoIsPublic` in firestore.rules, which is
/// the authoritative version of this check.
struct Video: Codable, Identifiable, Hashable {
    enum Visibility: String, Codable {
        case `public`, `private`
    }

    enum Status: String, Codable {
        // "generating" — an on-demand lesson (phase-07): Claude and GolpoAI
        // are still working, and playbackURL/durationSeconds/sizeBytes are
        // all null in Firestore until this flips to `ready`.
        case pending, uploading, generating, ready, failed
    }

    @DocumentID var id: String?
    var topicId: String
    var topicTitle: String
    var categoryId: String
    var topicVisibility: Visibility
    var title: String
    var description: String
    var order: Int
    // Optional, not because a *ready* video can lack one — it can't — but
    // because an on-demand lesson's doc exists (status == .generating)
    // before GolpoAI has produced anything to play. Every call site that
    // reaches these already only ever sees `.ready` videos (the feed query
    // filters on status server-side), so unwrapping there is safe.
    var playbackURL: String? = nil
    /// Non-nil only for on-demand lessons — the watermark-burned copy
    /// shown to a viewer whose tier doesn't include clean downloads
    /// (phase-07 §4/§7). `nil` for every curated (Creator-uploaded) video,
    /// which has no watermarking concept at all.
    var watermarkedPlaybackURL: String? = nil
    var thumbnailURL: String?
    var durationSeconds: Double? = nil
    var aspectRatio: Double
    var sizeBytes: Int? = nil
    var transcript: String?
    var visibility: Visibility
    var status: Status
    var statusMessage: String?
    var createdBy: String
    var createdAt: Date?
    var updatedAt: Date?
    var publishedAt: Date?
    var hasQuiz: Bool
    var likeCount: Int
    var commentCount: Int
    var viewCount: Int
    var completionCount: Int
    var isDeleted: Bool

    // ---- Phase 7: on-demand lessons ---------------------------------------
    // All optional and all absent from every curated video's document —
    // `createVideoUpload`/`finalizeVideoUpload` never write them — so any of
    // these being non-nil is itself the signal a video came from the
    // on-demand pipeline rather than a Creator upload.

    /// `"on_demand"` for a lesson generated by `createOnDemandLesson`;
    /// absent (nil) for a curated upload.
    var generationSource: String? = nil
    /// `true` once `shareLessonToSocial` has made this lesson's topic and
    /// video public — gates whether the "Share to Social" action should
    /// still be offered.
    var sharedToSocial: Bool? = nil
    /// `true` for a lesson created through the developer API
    /// (`functions/src/api/lessonsApi.ts`) rather than the app's own Create
    /// flow — these are excluded from Social and can't be shared to it
    /// (`shareLessonToSocial` rejects them server-side too).
    var originatedFromApi: Bool? = nil
    /// What was actually debited from the learner's wallet for this lesson,
    /// in cents — shown in My Lessons as a receipt, not recomputed
    /// client-side from `tiers.ts`'s pricing table.
    var costChargedCents: Int? = nil

    var isOnDemandLesson: Bool { generationSource == "on_demand" }
}
