#!/usr/bin/env python3
"""
Generates the bundled JSON content for the Shui iOS app:
  - civics_questions.json  (all 100 official USCIS civics test questions)
  - lessons.json           (flagship whiteboard-narrative lesson scripts)
  - current_officials.json (time-sensitive answers, kept out of source code)
  - state_capitals.json    (static per-state facts)
  - character.json         (tutor character dialogue lines)

Run with: python3 scripts/generate_content.py
Writes into Shui/Resources/Content/.

Content accuracy note: the 100 questions and their official acceptable
answers reflect the standard USCIS civics test. Time-sensitive answers
(current President, VP, Speaker, Chief Justice, and each user's own
Senators/Representative/Governor) are deliberately left as data to be
filled in / updated rather than hard-coded, since baking in a specific
name would silently go stale. See current_officials.json and the
"Your Local Officials" onboarding step.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "Shui", "Resources", "Content")

# ---------------------------------------------------------------------------
# Categories (mirrors the official USCIS grouping)
# ---------------------------------------------------------------------------
GOV_PRINCIPLES = "gov_principles"
GOV_SYSTEM = "gov_system"
GOV_RIGHTS = "gov_rights"
HIST_COLONIAL = "history_colonial"
HIST_1800S = "history_1800s"
HIST_RECENT = "history_recent"
GEOGRAPHY = "geography"
SYMBOLS = "symbols"
HOLIDAYS = "holidays"

NONE, NATIONAL, USER_STATE, STATE_CAPITAL = "none", "nationalOfficeholder", "userStateOfficeholder", "userStateCapital"

def q(id, category, questionEN, answersEN, explanationVI, quickFactEN,
      requiredAnswerCount=1, dynamicType=NONE, officeholderRole=None, lessonId=None):
    return {
        "id": id,
        "category": category,
        "questionEN": questionEN,
        "answersEN": answersEN,
        "requiredAnswerCount": requiredAnswerCount,
        "explanationVI": explanationVI,
        "quickFactEN": quickFactEN,
        "dynamicType": dynamicType,
        "officeholderRole": officeholderRole,
        "lessonId": lessonId or f"lsn_{id:03d}",
    }

QUESTIONS = [
q(1, GOV_PRINCIPLES, "What is the supreme law of the land?",
  ["the Constitution"],
  "Hiến pháp giống như \"luật của mọi luật\" — bất cứ luật nào của tiểu bang hay liên bang đều phải tuân theo nó. Khi bạn nhớ Hiến pháp là \"luật tối cao\", bạn sẽ hiểu tại sao mọi tranh chấp pháp lý lớn ở Mỹ cuối cùng đều quay về văn bản này.",
  "The Constitution outranks every other law in the country.",
  lessonId="lsn_001"),
q(2, GOV_PRINCIPLES, "What does the Constitution do?",
  ["sets up the government", "defines the government", "protects basic rights of Americans"],
  "Hiến pháp làm ba việc: thành lập chính phủ, quy định cách chính phủ hoạt động, và bảo vệ các quyền cơ bản của người dân. Hãy nghĩ nó như bản thiết kế (blueprint) của cả một ngôi nhà quốc gia.",
  "It sets up, defines, and protects rights within the government."),
q(3, GOV_PRINCIPLES, "The idea of self-government is in the first three words of the Constitution. What are these words?",
  ["We the People"],
  "\"We the People\" nghĩa là chính người dân — không phải vua hay hoàng đế — mới là người nắm quyền lực. Đây là ba từ mở đầu của Hiến pháp và tóm tắt toàn bộ tinh thần dân chủ Mỹ.",
  "\"We the People\" opens the Constitution and means the people hold the power."),
q(4, GOV_PRINCIPLES, "What is an amendment?",
  ["a change (to the Constitution)", "an addition (to the Constitution)"],
  "Một \"amendment\" là một điều khoản được thêm vào hoặc sửa đổi trong Hiến pháp. Những người soạn thảo Hiến pháp biết rằng đất nước sẽ thay đổi theo thời gian, nên họ để lại cách để cập nhật văn bản này.",
  "An amendment is a change or addition to the Constitution."),
q(5, GOV_PRINCIPLES, "What do we call the first ten amendments to the Constitution?",
  ["the Bill of Rights"],
  "Mười tu chính án đầu tiên được gọi chung là \"Bill of Rights\" (Tuyên ngôn Nhân quyền). Chúng bảo vệ những quyền tự do cá nhân quan trọng nhất, như tự do ngôn luận và tự do tôn giáo.",
  "The first 10 amendments together are called the Bill of Rights.",
  lessonId="lsn_006"),
q(6, GOV_PRINCIPLES, "What is one right or freedom from the First Amendment?",
  ["speech", "religion", "assembly", "press", "petition the government"],
  "Tu chính án thứ nhất bảo vệ năm quyền cùng lúc: nói tự do, theo tôn giáo mình chọn, tụ họp hòa bình, báo chí tự do, và quyền kiến nghị với chính phủ. Hãy tưởng tượng năm ngón tay trên một bàn tay — mỗi ngón là một quyền tự do.",
  "The First Amendment protects speech, religion, assembly, press, and petition.",
  lessonId="lsn_006"),
q(7, GOV_PRINCIPLES, "How many amendments does the Constitution have?",
  ["twenty-seven (27)"],
  "Hiến pháp có tổng cộng 27 tu chính án, được thêm vào dần dần từ năm 1791 cho đến năm 1992. Mười cái đầu tiên đến cùng lúc (Bill of Rights), còn 17 cái còn lại được thêm qua hơn 200 năm lịch sử.",
  "27 amendments have been added to the Constitution since 1791."),
q(8, GOV_PRINCIPLES, "What did the Declaration of Independence do?",
  ["announced our independence (from Great Britain)", "declared our independence (from Great Britain)", "said that the United States is free (from Great Britain)"],
  "Bản Tuyên ngôn Độc lập là lời tuyên bố chính thức rằng 13 thuộc địa không còn là một phần của nước Anh nữa. Nó giống như một \"lá thư chia tay\" rất trang trọng gửi đến vua Anh.",
  "It announced that the colonies were independent from Great Britain.",
  lessonId="lsn_063"),
q(9, GOV_PRINCIPLES, "What are two rights in the Declaration of Independence?",
  ["life", "liberty", "pursuit of happiness"],
  "Bản Tuyên ngôn nói rằng mọi người sinh ra đều có quyền được sống, được tự do, và được mưu cầu hạnh phúc. Đây là ba quyền nổi tiếng nhất trong lịch sử nước Mỹ — bạn chỉ cần nhớ hai trong ba là đủ trả lời.",
  "Life, liberty, and the pursuit of happiness are named as rights.", requiredAnswerCount=2),
q(10, GOV_PRINCIPLES, "What is freedom of religion?",
  ["You can practice any religion, or not practice a religion."],
  "Ở Mỹ, bạn có quyền theo bất kỳ tôn giáo nào bạn muốn — Phật giáo, Công giáo, Tin lành, Hồi giáo, hay không theo tôn giáo nào cả. Chính phủ không được ép buộc hay cấm đoán niềm tin tôn giáo của bạn.",
  "You may practice any religion, or none at all."),
q(11, GOV_PRINCIPLES, "What is the economic system in the United States?",
  ["capitalist economy", "market economy"],
  "Nước Mỹ theo hệ thống kinh tế thị trường (capitalist/market economy), nghĩa là cá nhân và doanh nghiệp tự do sở hữu tài sản, kinh doanh, và cạnh tranh, thay vì chính phủ kiểm soát mọi thứ.",
  "The U.S. runs on a capitalist, market-based economy."),
q(12, GOV_PRINCIPLES, "What is the \"rule of law\"?",
  ["Everyone must follow the law", "Leaders must obey the law", "Government must obey the law", "No one is above the law"],
  "\"Rule of law\" nghĩa là không ai đứng trên luật pháp — kể cả tổng thống. Đây là nguyên tắc then chốt khiến nước Mỹ khác với những nơi mà lãnh đạo có thể tự đặt mình ngoài vòng pháp luật.",
  "No one — not even the President — is above the law."),

q(13, GOV_SYSTEM, "Name one branch or part of the government.",
  ["Congress", "legislative", "President", "executive", "the courts", "judicial"],
  "Chính phủ Mỹ chia làm ba nhánh: Quốc hội (làm luật), Tổng thống (thi hành luật), và Tòa án (giải thích luật). Ba nhánh này giống như ba chân của một cái ghế — cần cả ba để đứng vững.",
  "The three branches are Congress, the President, and the courts.",
  lessonId="lsn_013"),
q(14, GOV_SYSTEM, "What stops one branch of government from becoming too powerful?",
  ["checks and balances", "separation of powers"],
  "Mỗi nhánh chính phủ có quyền \"kiểm soát\" hai nhánh còn lại — ví dụ Tổng thống có thể phủ quyết luật, nhưng Quốc hội có thể bác bỏ phủ quyết đó. Hệ thống này gọi là \"checks and balances\", giúp không ai nắm quá nhiều quyền lực.",
  "\"Checks and balances\" keeps power spread across the branches.",
  lessonId="lsn_013"),
q(15, GOV_SYSTEM, "Who is in charge of the executive branch?",
  ["the President"],
  "Tổng thống đứng đầu nhánh hành pháp (executive branch) — nhánh chịu trách nhiệm thi hành các luật mà Quốc hội đã thông qua.",
  "The President leads the executive branch."),
q(16, GOV_SYSTEM, "Who makes federal laws?",
  ["Congress", "Senate and House (of Representatives)", "(U.S. or national) legislature"],
  "Quốc hội — gồm Thượng viện và Hạ viện — là nơi làm ra luật liên bang. Đây là nhánh lập pháp (legislative branch) của chính phủ.",
  "Congress — the Senate and House together — writes federal laws.",
  lessonId="lsn_017"),
q(17, GOV_SYSTEM, "What are the two parts of the U.S. Congress?",
  ["the Senate and House (of Representatives)"],
  "Quốc hội Mỹ có hai viện: Thượng viện (Senate) với 100 Thượng nghị sĩ, và Hạ viện (House of Representatives) với 435 Dân biểu. Hai viện phải cùng đồng ý thì một dự luật mới trở thành luật.",
  "Congress has two chambers: the Senate and the House.",
  lessonId="lsn_017"),
q(18, GOV_SYSTEM, "How many U.S. Senators are there?",
  ["one hundred (100)"],
  "Có đúng 100 Thượng nghị sĩ — mỗi tiểu bang, dù lớn hay nhỏ, đều có đúng 2 người đại diện tại Thượng viện. 50 tiểu bang nhân 2 bằng 100.",
  "Each of the 50 states elects exactly 2 Senators — 100 total.",
  lessonId="lsn_017"),
q(19, GOV_SYSTEM, "We elect a U.S. Senator for how many years?",
  ["six (6)"],
  "Nhiệm kỳ của một Thượng nghị sĩ kéo dài 6 năm — dài hơn nhiệm kỳ 2 năm của Dân biểu Hạ viện, giúp Thượng viện có sự ổn định hơn.",
  "A Senator serves a six-year term."),
q(20, GOV_SYSTEM, "Who is one of your state's U.S. Senators now?",
  [],
  "Câu trả lời tùy vào tiểu bang bạn đang sống, và có thể thay đổi sau mỗi cuộc bầu cử. Hãy điền tên hai Thượng nghị sĩ của tiểu bang bạn trong phần \"Cán bộ địa phương của tôi\" để ứng dụng nhắc bạn ôn đúng tên.",
  "Answer depends on your state — add it in your profile.",
  dynamicType=USER_STATE, officeholderRole="stateSenators"),
q(21, GOV_SYSTEM, "The House of Representatives has how many voting members?",
  ["four hundred thirty-five (435)"],
  "Hạ viện có 435 Dân biểu có quyền biểu quyết. Số ghế của mỗi tiểu bang trong Hạ viện phụ thuộc vào dân số — tiểu bang đông dân như California có nhiều Dân biểu hơn tiểu bang ít dân như Wyoming.",
  "The House has 435 voting members, split by state population.",
  lessonId="lsn_021"),
q(22, GOV_SYSTEM, "We elect a U.S. Representative for how many years?",
  ["two (2)"],
  "Dân biểu Hạ viện chỉ phục vụ 2 năm một nhiệm kỳ — ngắn hơn nhiều so với 6 năm của Thượng nghị sĩ, vì Hạ viện được thiết kế để phản ánh sát nhất ý muốn hiện tại của người dân.",
  "A Representative serves a two-year term."),
q(23, GOV_SYSTEM, "Name your U.S. Representative.",
  [],
  "Câu trả lời tùy vào khu vực bầu cử (district) nơi bạn sống. Hãy tra cứu và lưu tên vị Dân biểu của bạn trong phần cài đặt hồ sơ.",
  "Answer depends on your district — add it in your profile.",
  dynamicType=USER_STATE, officeholderRole="representative"),
q(24, GOV_SYSTEM, "Who does a U.S. Senator represent?",
  ["all people of the state"],
  "Một Thượng nghị sĩ đại diện cho toàn bộ người dân của cả tiểu bang — không chỉ một thành phố hay một khu vực nhỏ như Dân biểu Hạ viện.",
  "A Senator represents everyone in their entire state."),
q(25, GOV_SYSTEM, "Why do some states have more Representatives than other states?",
  ["(because of) the state's population", "(because) they have more people"],
  "Số Dân biểu của một tiểu bang tỷ lệ thuận với dân số — tiểu bang càng đông người thì càng có nhiều ghế ở Hạ viện. Cứ sau mỗi cuộc thống kê dân số (census) 10 năm một lần, số ghế có thể được phân bổ lại.",
  "More population means more seats in the House."),
q(26, GOV_SYSTEM, "We elect a President for how many years?",
  ["four (4)"],
  "Nhiệm kỳ Tổng thống kéo dài 4 năm, và một người chỉ được làm Tổng thống tối đa 2 nhiệm kỳ (8 năm) theo Tu chính án 22.",
  "The President serves a four-year term."),
q(27, GOV_SYSTEM, "In what month do we vote for President?",
  ["November"],
  "Cuộc bầu cử Tổng thống luôn diễn ra vào tháng 11, cụ thể là ngày thứ Ba đầu tiên sau ngày thứ Hai đầu tiên của tháng — truyền thống này có từ thế kỷ 19 khi nông dân cần thời gian thu hoạch xong mùa màng trước khi đi bỏ phiếu.",
  "Presidential elections happen every November."),
q(28, GOV_SYSTEM, "What is the name of the President of the United States now?",
  [],
  "Tên Tổng thống hiện tại thay đổi theo từng cuộc bầu cử, nên ứng dụng luôn lấy thông tin này từ phần \"Cán bộ đương nhiệm\" được cập nhật định kỳ thay vì ghi cứng trong bài học — hãy kiểm tra phần đó để có câu trả lời mới nhất.",
  "Check \"Current Officials\" in the app for today's answer.",
  dynamicType=NATIONAL, officeholderRole="president"),
q(29, GOV_SYSTEM, "What is the name of the Vice President of the United States now?",
  [],
  "Cũng giống như câu hỏi về Tổng thống, tên Phó Tổng thống hiện tại được cập nhật trong phần \"Cán bộ đương nhiệm\" của ứng dụng.",
  "Check \"Current Officials\" in the app for today's answer.",
  dynamicType=NATIONAL, officeholderRole="vicePresident"),
q(30, GOV_SYSTEM, "If the President can no longer serve, who becomes President?",
  ["the Vice President"],
  "Nếu Tổng thống không thể tiếp tục làm việc — vì qua đời, từ chức, hay mất năng lực — thì Phó Tổng thống sẽ lên thay ngay lập tức. Đây gọi là \"thứ tự kế vị\" (line of succession).",
  "The Vice President immediately takes over."),
q(31, GOV_SYSTEM, "If both the President and the Vice President can no longer serve, who becomes President?",
  ["the Speaker of the House"],
  "Nếu cả Tổng thống lẫn Phó Tổng thống đều không thể phục vụ, người tiếp theo trong danh sách kế vị là Chủ tịch Hạ viện (Speaker of the House).",
  "Next in line after the Vice President is the Speaker of the House."),
q(32, GOV_SYSTEM, "Who is the Commander in Chief of the military?",
  ["the President"],
  "Tổng thống là Tổng Tư lệnh (Commander in Chief) của toàn bộ quân đội Hoa Kỳ, bao gồm Lục quân, Hải quân, Không quân, Thủy quân lục chiến, và Tuần duyên.",
  "The President commands all U.S. armed forces."),
q(33, GOV_SYSTEM, "Who signs bills to become laws?",
  ["the President"],
  "Sau khi Quốc hội thông qua một dự luật, Tổng thống ký tên vào đó để nó chính thức trở thành luật.",
  "The President signs bills passed by Congress into law."),
q(34, GOV_SYSTEM, "Who vetoes bills?",
  ["the President"],
  "Tổng thống cũng có quyền phủ quyết (veto) — từ chối ký một dự luật, gửi trả lại cho Quốc hội. Đây chính là ví dụ điển hình của \"checks and balances\" mà chúng ta đã học ở câu 14.",
  "The President can veto (reject) a bill from Congress."),
q(35, GOV_SYSTEM, "What does the President's Cabinet do?",
  ["advises the President"],
  "Nội các (Cabinet) gồm những người đứng đầu các bộ như Bộ Ngoại giao hay Bộ Quốc phòng — công việc của họ là cố vấn cho Tổng thống trong lĩnh vực chuyên môn của mình.",
  "The Cabinet advises the President on major issues."),
q(36, GOV_SYSTEM, "What are two Cabinet-level positions?",
  ["Secretary of Agriculture", "Secretary of Commerce", "Secretary of Defense", "Secretary of Education",
   "Secretary of Energy", "Secretary of Health and Human Services", "Secretary of Homeland Security",
   "Secretary of Housing and Urban Development", "Secretary of the Interior", "Secretary of Labor",
   "Secretary of State", "Secretary of Transportation", "Secretary of the Treasury", "Secretary of Veterans Affairs",
   "Attorney General", "Vice President"],
  "Có 15 vị trí cấp Nội các, mỗi người đứng đầu một bộ như Bộ Ngoại giao (State), Bộ Quốc phòng (Defense), hay Bộ Tư pháp (đứng đầu là Attorney General). Bạn chỉ cần nhớ tên hai bộ là đủ.",
  "Cabinet members lead departments like State, Defense, or Treasury.", requiredAnswerCount=2),
q(37, GOV_SYSTEM, "What does the judicial branch do?",
  ["reviews laws", "explains laws", "resolves disputes (disagreements)", "decides if a law goes against the Constitution"],
  "Nhánh tư pháp (judicial branch) — tức hệ thống tòa án — có nhiệm vụ giải thích luật, giải quyết tranh chấp, và quyết định xem một luật có vi phạm Hiến pháp hay không.",
  "The courts interpret laws and settle disputes.",
  lessonId="lsn_013"),
q(38, GOV_SYSTEM, "What is the highest court in the United States?",
  ["the Supreme Court"],
  "Tòa án Tối cao (Supreme Court) là tòa án cao nhất nước Mỹ — quyết định của nó là quyết định cuối cùng, không thể kháng cáo lên đâu khác nữa.",
  "The Supreme Court is the highest court in the country."),
q(39, GOV_SYSTEM, "How many justices are on the Supreme Court?",
  ["nine (9)"],
  "Tòa án Tối cao hiện có 9 thẩm phán (justices). Con số này do luật Quốc hội quy định, không phải do Hiến pháp cố định, nhưng đã giữ nguyên ở mức 9 từ năm 1869.",
  "There are nine justices on the Supreme Court."),
q(40, GOV_SYSTEM, "Who is the Chief Justice of the United States now?",
  [],
  "Tên vị Chánh án hiện tại được cập nhật trong phần \"Cán bộ đương nhiệm\" của ứng dụng, vì vị trí này có thể thay đổi khi có người mới được bổ nhiệm.",
  "Check \"Current Officials\" in the app for today's answer.",
  dynamicType=NATIONAL, officeholderRole="chiefJustice"),
q(41, GOV_SYSTEM, "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?",
  ["to print money", "to declare war", "to create an army", "to make treaties"],
  "Chính phủ liên bang nắm những quyền lớn ảnh hưởng cả nước: in tiền, tuyên chiến, lập quân đội, và ký hiệp ước với nước ngoài — những việc mà từng tiểu bang riêng lẻ không thể tự làm.",
  "Federal powers include printing money, declaring war, and treaties."),
q(42, GOV_SYSTEM, "Under our Constitution, some powers belong to the states. What is one power of the states?",
  ["provide schooling and education", "provide protection (police)", "provide safety (fire departments)",
   "give a driver's license", "approve zoning and land use"],
  "Từng tiểu bang tự quản lý những việc gần gũi với đời sống hàng ngày: trường học, cảnh sát, cứu hỏa, cấp bằng lái xe, và quy hoạch đất đai.",
  "States handle schools, police, fire departments, and driver's licenses."),
q(43, GOV_SYSTEM, "Who is the Governor of your state now?",
  [],
  "Câu trả lời tùy vào tiểu bang bạn sống. Hãy thêm tên Thống đốc tiểu bang của bạn vào hồ sơ để ôn tập chính xác.",
  "Answer depends on your state — add it in your profile.",
  dynamicType=USER_STATE, officeholderRole="governor"),
q(44, GOV_SYSTEM, "What is the capital of your state?",
  [],
  "Thủ phủ (capital) của mỗi tiểu bang thường không phải là thành phố lớn nhất — ví dụ thủ phủ California là Sacramento, không phải Los Angeles. Ứng dụng sẽ tự điền câu trả lời đúng dựa trên tiểu bang bạn chọn khi đăng ký.",
  "Your state's capital is filled in automatically from your profile.",
  dynamicType=STATE_CAPITAL),
q(45, GOV_SYSTEM, "What are the two major political parties in the United States?",
  ["Democratic and Republican"],
  "Hai đảng chính trị lớn nhất nước Mỹ là Đảng Dân chủ (Democratic) và Đảng Cộng hòa (Republican). Hầu hết các cuộc bầu cử đều là cuộc đua giữa ứng viên của hai đảng này.",
  "The two major parties are Democratic and Republican."),
q(46, GOV_SYSTEM, "What is the political party of the President now?",
  [],
  "Đảng của Tổng thống thay đổi theo từng cuộc bầu cử — hãy kiểm tra phần \"Cán bộ đương nhiệm\" để có câu trả lời cập nhật.",
  "Check \"Current Officials\" in the app for today's answer.",
  dynamicType=NATIONAL, officeholderRole="presidentParty"),
q(47, GOV_SYSTEM, "What is the name of the Speaker of the House of Representatives now?",
  [],
  "Chủ tịch Hạ viện (Speaker of the House) do các Dân biểu bầu chọn và có thể thay đổi. Hãy kiểm tra phần \"Cán bộ đương nhiệm\" để có tên chính xác.",
  "Check \"Current Officials\" in the app for today's answer.",
  dynamicType=NATIONAL, officeholderRole="speakerOfHouse"),

q(48, GOV_RIGHTS, "There are four amendments to the Constitution about who can vote. Describe one of them.",
  ["Citizens eighteen (18) and older (can vote)", "You don't have to pay (a poll tax) to vote",
   "Any citizen can vote (women and men can vote)", "A male citizen of any race (can vote)"],
  "Bốn tu chính án mở rộng quyền bầu cử theo thời gian: cho phép mọi chủng tộc bầu cử, cho phép phụ nữ bầu cử, bỏ thuế thân khi đi bầu, và hạ tuổi bầu cử xuống 18. Mỗi tu chính án là một bước tiến để nước Mỹ công bằng hơn.",
  "Amendments expanded voting to all races, women, and age 18+."),
q(49, GOV_RIGHTS, "What is one responsibility that is only for United States citizens?",
  ["serve on a jury", "vote in a federal election"],
  "Chỉ có công dân Mỹ mới có trách nhiệm phục vụ bồi thẩm đoàn (jury) và bỏ phiếu trong bầu cử liên bang — đây là những nghĩa vụ đi kèm với đặc quyền công dân.",
  "Only citizens serve on juries and vote in federal elections."),
q(50, GOV_RIGHTS, "Name one right only for United States citizens.",
  ["vote in a federal election", "run for federal office"],
  "Chỉ công dân mới được bỏ phiếu trong bầu cử liên bang và ra tranh cử các chức vụ liên bang. Đây là hai quyền lợi lớn mà việc nhập tịch mang lại.",
  "Only citizens may vote federally or run for federal office."),
q(51, GOV_RIGHTS, "What are two rights of everyone living in the United States?",
  ["freedom of expression", "freedom of speech", "freedom of assembly", "freedom to petition the government",
   "freedom of worship", "the right to bear arms"],
  "Khác với hai câu trước, những quyền này thuộc về TẤT CẢ mọi người sống ở Mỹ, không chỉ công dân — bao gồm tự do ngôn luận, tự do tụ họp, tự do tôn giáo, và quyền mang vũ khí.",
  "Rights like free speech and worship belong to everyone, not just citizens.", requiredAnswerCount=2),
q(52, GOV_RIGHTS, "What do we show loyalty to when we say the Pledge of Allegiance?",
  ["the United States", "the flag"],
  "Khi đọc Lời tuyên thệ trung thành (Pledge of Allegiance), người Mỹ thể hiện lòng trung thành với lá cờ và với đất nước Hoa Kỳ.",
  "The Pledge shows loyalty to the United States and its flag."),
q(53, GOV_RIGHTS, "What is one promise you make when you become a United States citizen?",
  ["give up loyalty to other countries", "defend the Constitution and laws of the United States",
   "obey the laws of the United States", "serve in the U.S. military (if needed)",
   "serve (do important work for) the nation (if needed)", "be loyal to the United States"],
  "Khi tuyên thệ nhập tịch, bạn hứa từ bỏ trung thành với nước khác, bảo vệ Hiến pháp, tuân thủ luật pháp Mỹ, và sẵn sàng phục vụ đất nước khi cần. Đây là lời thề trang trọng đánh dấu bạn chính thức trở thành công dân.",
  "New citizens promise loyalty to and defense of the United States."),
q(54, GOV_RIGHTS, "How old do citizens have to be to vote for President?",
  ["eighteen (18)"],
  "Bạn phải đủ 18 tuổi trở lên mới được bỏ phiếu bầu Tổng thống, theo Tu chính án 26.",
  "Citizens must be 18 or older to vote for President."),
q(55, GOV_RIGHTS, "What are two ways that Americans can participate in their democracy?",
  ["vote", "join a political party", "help with a campaign", "join a civic group", "join a community group",
   "give an elected official your opinion", "call Senators and Representatives", "publicly support or oppose an issue",
   "run for office", "write to a newspaper"],
  "Có rất nhiều cách để tham gia vào nền dân chủ: bỏ phiếu, gia nhập một đảng phái, tham gia vận động tranh cử, gọi điện cho dân biểu, hay thậm chí tự mình ra tranh cử. Dân chủ không chỉ là chuyện của ngày bầu cử.",
  "Ways to participate include voting, campaigning, or contacting officials.", requiredAnswerCount=2),
q(56, GOV_RIGHTS, "When is the last day you can send in federal income tax forms?",
  ["April 15"],
  "Hạn chót nộp tờ khai thuế thu nhập liên bang hằng năm là ngày 15 tháng 4.",
  "Federal tax forms are due by April 15 each year."),
q(57, GOV_RIGHTS, "When must all men register for the Selective Service?",
  ["at age eighteen (18)", "between eighteen (18) and twenty-six (26)"],
  "Mọi nam giới sống ở Mỹ, kể cả người không phải công dân, phải đăng ký Selective Service (danh sách quân dịch dự bị) trong khoảng từ 18 đến 26 tuổi.",
  "Men must register for Selective Service between ages 18 and 26."),

q(58, HIST_COLONIAL, "What is one reason colonists came to America?",
  ["freedom", "political liberty", "religious freedom", "economic opportunity", "practice their religion",
   "escape persecution"],
  "Người di dân đến Mỹ vì nhiều lý do: tìm tự do tôn giáo, thoát khỏi sự đàn áp, tìm cơ hội kinh tế mới, hay đơn giản là muốn tự do chính trị. Câu chuyện này rất giống hành trình của nhiều gia đình người Việt đến Mỹ sau này — đi tìm một khởi đầu mới.",
  "Colonists sought religious freedom and economic opportunity.",
  lessonId="lsn_058"),
q(59, HIST_COLONIAL, "Who lived in America before the Europeans arrived?",
  ["American Indians", "Native Americans"],
  "Trước khi người châu Âu đặt chân đến, hàng trăm bộ lạc người bản địa (American Indians / Native Americans) đã sinh sống trên khắp lục địa này hàng ngàn năm.",
  "Native Americans lived in America long before Europeans arrived."),
q(60, HIST_COLONIAL, "What group of people was taken to America and sold as slaves?",
  ["Africans", "people from Africa"],
  "Hàng triệu người châu Phi bị bắt cóc và đưa đến Mỹ để bán làm nô lệ — đây là một phần đau thương nhưng quan trọng của lịch sử Mỹ mà chúng ta cần hiểu rõ.",
  "Enslaved people were forcibly brought from Africa."),
q(61, HIST_COLONIAL, "Why did the colonists fight the British?",
  ["because of high taxes (taxation without representation)", "because the British army stayed in their houses (boarding, quartering)",
   "because they didn't have self-government"],
  "Người thuộc địa nổi giận vì bị đánh thuế cao mà không có đại diện trong Quốc hội Anh — khẩu hiệu nổi tiếng của họ là \"No taxation without representation\" (không đại diện thì không đóng thuế).",
  "Colonists rebelled over high taxes with no representation in Parliament.",
  lessonId="lsn_061"),
q(62, HIST_COLONIAL, "Who wrote the Declaration of Independence?",
  ["(Thomas) Jefferson"],
  "Thomas Jefferson là người chấp bút chính cho bản Tuyên ngôn Độc lập năm 1776, dù ông có sự góp ý của một ủy ban gồm nhiều người khác.",
  "Thomas Jefferson wrote the Declaration of Independence.",
  lessonId="lsn_063"),
q(63, HIST_COLONIAL, "When was the Declaration of Independence adopted?",
  ["July 4, 1776"],
  "Ngày 4 tháng 7 năm 1776 là ngày bản Tuyên ngôn Độc lập được thông qua — đây cũng chính là ngày lễ Quốc khánh Mỹ (Independence Day) mà bạn thấy pháo hoa mỗi năm.",
  "The Declaration was adopted on July 4, 1776.",
  lessonId="lsn_063"),
q(64, HIST_COLONIAL, "There were 13 original states. Name three.",
  ["New Hampshire", "Massachusetts", "Rhode Island", "Connecticut", "New York", "New Jersey", "Pennsylvania",
   "Delaware", "Maryland", "Virginia", "North Carolina", "South Carolina", "Georgia"],
  "13 thuộc địa ban đầu đều nằm dọc theo bờ biển phía Đông nước Mỹ ngày nay, trải dài từ New Hampshire ở phía Bắc xuống Georgia ở phía Nam. Hãy hình dung một dải đất hẹp ven biển — đó chính là nước Mỹ lúc mới lập quốc.",
  "The 13 original states stretched along the Atlantic coast.",
  requiredAnswerCount=3, lessonId="lsn_064"),
q(65, HIST_COLONIAL, "What happened at the Constitutional Convention?",
  ["The Constitution was written", "The Founding Fathers wrote the Constitution"],
  "Tại Hội nghị Lập hiến (Constitutional Convention) năm 1787 ở Philadelphia, các nhà lập quốc đã cùng nhau soạn ra bản Hiến pháp Hoa Kỳ.",
  "The Constitution was written at the Constitutional Convention.",
  lessonId="lsn_066"),
q(66, HIST_COLONIAL, "When was the Constitution written?",
  ["1787"],
  "Hiến pháp được soạn thảo vào năm 1787 tại Philadelphia, 11 năm sau khi tuyên bố độc lập — các nhà lập quốc cần thời gian đó để thống nhất cách vận hành chính phủ mới.",
  "The Constitution was written in 1787 in Philadelphia.",
  lessonId="lsn_066"),
q(67, HIST_COLONIAL, "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.",
  ["(James) Madison", "(Alexander) Hamilton", "(John) Jay", "Publius"],
  "The Federalist Papers là loạt bài luận thuyết phục người dân ủng hộ Hiến pháp mới, được viết bởi James Madison, Alexander Hamilton, và John Jay dưới bút danh chung \"Publius\".",
  "James Madison, Alexander Hamilton, and John Jay wrote the Federalist Papers."),
q(68, HIST_COLONIAL, "What is one thing Benjamin Franklin is famous for?",
  ["U.S. diplomat", "oldest member of the Constitutional Convention", "first Postmaster General of the United States",
   "writer of \"Poor Richard's Almanac\"", "started the first free libraries"],
  "Benjamin Franklin nổi tiếng với rất nhiều vai trò: nhà ngoại giao, người sáng lập hệ thống thư viện công cộng đầu tiên, và là thành viên lớn tuổi nhất tại Hội nghị Lập hiến.",
  "Franklin was a diplomat, inventor, and founding father."),
q(69, HIST_COLONIAL, "Who is the \"Father of Our Country\"?",
  ["(George) Washington"],
  "George Washington được gọi là \"Cha đẻ của Tổ quốc\" vì ông là vị tướng dẫn dắt cuộc Cách mạng và là Tổng thống đầu tiên của nước Mỹ.",
  "George Washington is called the \"Father of Our Country.\""),
q(70, HIST_COLONIAL, "Who was the first President?",
  ["(George) Washington"],
  "George Washington trở thành Tổng thống đầu tiên của Hoa Kỳ vào năm 1789, và ông đã đặt ra nhiều truyền thống mà các Tổng thống sau này vẫn noi theo, như chỉ làm 2 nhiệm kỳ.",
  "George Washington was the first U.S. President."),

q(71, HIST_1800S, "What territory did the United States buy from France in 1803?",
  ["the Louisiana Territory", "Louisiana"],
  "Năm 1803, Mỹ mua vùng đất Louisiana rộng lớn từ Pháp, gần như nhân đôi diện tích đất nước chỉ trong một thương vụ — đây gọi là \"Louisiana Purchase\".",
  "The U.S. bought the Louisiana Territory from France in 1803."),
q(72, HIST_1800S, "Name one war fought by the United States in the 1800s.",
  ["War of 1812", "Mexican-American War", "Civil War", "Spanish-American War"],
  "Trong thế kỷ 19, Mỹ trải qua nhiều cuộc chiến: chiến tranh 1812 với Anh, chiến tranh với Mexico, Nội chiến, và chiến tranh Tây Ban Nha-Mỹ.",
  "1800s wars include the War of 1812, Mexican-American War, and Civil War."),
q(73, HIST_1800S, "Name the U.S. war between the North and the South.",
  ["the Civil War", "the War between the States"],
  "Cuộc chiến giữa miền Bắc và miền Nam gọi là Nội chiến (Civil War), diễn ra từ 1861 đến 1865 — một trong những giai đoạn đẫm máu và quan trọng nhất lịch sử Mỹ.",
  "The Civil War (1861–1865) was fought between North and South.",
  lessonId="lsn_073"),
q(74, HIST_1800S, "Name one problem that led to the Civil War.",
  ["slavery", "economic reasons", "states' rights"],
  "Nguyên nhân chính dẫn đến Nội chiến là chế độ nô lệ, cùng với những bất đồng về quyền của tiểu bang và lợi ích kinh tế giữa miền Bắc công nghiệp và miền Nam nông nghiệp.",
  "Slavery was the central cause of the Civil War.",
  lessonId="lsn_073"),
q(75, HIST_1800S, "What was one important thing that Abraham Lincoln did?",
  ["freed the slaves (Emancipation Proclamation)", "saved (or preserved) the Union",
   "led the United States during the Civil War"],
  "Abraham Lincoln dẫn dắt nước Mỹ qua Nội chiến, giữ cho đất nước không bị chia cắt, và ký Tuyên ngôn Giải phóng Nô lệ (Emancipation Proclamation).",
  "Lincoln led the U.S. through the Civil War and freed enslaved people.",
  lessonId="lsn_075"),
q(76, HIST_1800S, "What did the Emancipation Proclamation do?",
  ["freed the slaves", "freed slaves in the Confederacy", "freed slaves in the Confederate states",
   "freed slaves in most Southern states"],
  "Tuyên ngôn Giải phóng Nô lệ năm 1863 tuyên bố những người nô lệ ở các bang miền Nam ly khai được tự do — đây là bước ngoặt lớn hướng tới việc xóa bỏ hoàn toàn chế độ nô lệ.",
  "It declared enslaved people in the Confederate states free.",
  lessonId="lsn_075"),
q(77, HIST_1800S, "What did Susan B. Anthony do?",
  ["fought for women's rights", "fought for civil rights"],
  "Susan B. Anthony là nhà hoạt động đấu tranh không mệt mỏi cho quyền bầu cử của phụ nữ, góp phần quan trọng dẫn đến Tu chính án 19 cho phép phụ nữ đi bầu.",
  "Susan B. Anthony fought for women's right to vote."),

q(78, HIST_RECENT, "Name one war fought by the United States in the 1900s.",
  ["World War I", "World War II", "Korean War", "Vietnam War", "(Persian) Gulf War"],
  "Thế kỷ 20 chứng kiến Mỹ tham gia nhiều cuộc chiến lớn: Thế chiến I, Thế chiến II, chiến tranh Triều Tiên, chiến tranh Việt Nam, và chiến tranh Vùng Vịnh — nhiều người Việt tại Mỹ có mối liên hệ trực tiếp với giai đoạn lịch sử này.",
  "1900s wars include WWI, WWII, Korea, Vietnam, and the Gulf War."),
q(79, HIST_RECENT, "Who was President during World War I?",
  ["(Woodrow) Wilson"],
  "Woodrow Wilson là Tổng thống Mỹ trong suốt Thế chiến thứ Nhất (1914-1918).",
  "Woodrow Wilson was President during World War I."),
q(80, HIST_RECENT, "Who was President during the Great Depression and World War II?",
  ["(Franklin) Roosevelt"],
  "Franklin Roosevelt (thường viết tắt FDR) dẫn dắt nước Mỹ qua cả cuộc Đại Khủng hoảng kinh tế và phần lớn Thế chiến thứ Hai — ông là Tổng thống duy nhất phục vụ hơn 2 nhiệm kỳ.",
  "Franklin Roosevelt led the U.S. through the Depression and WWII."),
q(81, HIST_RECENT, "Who did the United States fight in World War II?",
  ["Japan, Germany, and Italy"],
  "Trong Thế chiến II, Mỹ và phe Đồng minh chiến đấu chống lại phe Trục gồm Nhật Bản, Đức, và Ý.",
  "The U.S. fought Japan, Germany, and Italy in WWII."),
q(82, HIST_RECENT, "Before he was President, Eisenhower was a general. What war was he in?",
  ["World War II"],
  "Trước khi làm Tổng thống, Dwight Eisenhower là vị tướng chỉ huy quân Đồng minh trong Thế chiến thứ Hai, nổi tiếng với chiến dịch đổ bộ Normandy.",
  "Eisenhower was a general in World War II."),
q(83, HIST_RECENT, "During the Cold War, what was the main concern of the United States?",
  ["Communism"],
  "Trong thời Chiến tranh Lạnh, mối lo ngại chính của Mỹ là sự lan rộng của chủ nghĩa Cộng sản — đây cũng là bối cảnh lịch sử gắn liền với cuộc chiến Việt Nam.",
  "The main Cold War concern was the spread of Communism."),
q(84, HIST_RECENT, "What movement tried to end racial discrimination?",
  ["civil rights (movement)"],
  "Phong trào Dân quyền (Civil Rights Movement) những năm 1950-1960 đấu tranh để chấm dứt sự phân biệt chủng tộc và đòi quyền bình đẳng cho người Mỹ gốc Phi.",
  "The civil rights movement fought to end racial discrimination."),
q(85, HIST_RECENT, "What did Martin Luther King, Jr. do?",
  ["fought for civil rights", "worked for equality for all Americans"],
  "Martin Luther King, Jr. là lãnh đạo nổi bật nhất của phong trào Dân quyền, nổi tiếng với bài diễn văn \"I Have a Dream\" và chủ trương đấu tranh bất bạo động.",
  "Dr. King led the civil rights movement through nonviolent protest."),
q(86, HIST_RECENT, "What major event happened on September 11, 2001, in the United States?",
  ["Terrorists attacked the United States"],
  "Ngày 11 tháng 9 năm 2001, những kẻ khủng bố đã tấn công nước Mỹ, bao gồm cả tòa tháp đôi World Trade Center ở New York — một sự kiện đã thay đổi sâu sắc chính sách an ninh của Mỹ.",
  "Terrorists attacked the U.S. on September 11, 2001."),
q(87, HIST_RECENT, "Name one American Indian tribe in the United States.",
  ["Cherokee", "Navajo", "Sioux", "Chippewa", "Choctaw", "Pueblo", "Apache", "Iroquois", "Creek", "Blackfeet",
   "Seminole", "Cheyenne", "Arawak", "Shawnee", "Mohegan", "Huron", "Oneida", "Lakota", "Crow", "Teton",
   "Hopi", "Inuit"],
  "Có hàng trăm bộ lạc người bản địa khác nhau trên khắp nước Mỹ — bạn chỉ cần nhớ tên một bộ lạc, ví dụ Cherokee, Navajo, hay Sioux, là đủ trả lời đúng.",
  "There are hundreds of Native American tribes — name any one."),

q(88, GEOGRAPHY, "Name one of the two longest rivers in the United States.",
  ["Missouri (River)", "Mississippi (River)"],
  "Hai con sông dài nhất nước Mỹ là sông Missouri và sông Mississippi. Sông Mississippi chảy từ Bắc xuống Nam, chia đôi đất nước gần như thành hai nửa Đông-Tây.",
  "The Missouri and Mississippi are the two longest U.S. rivers.",
  lessonId="lsn_088"),
q(89, GEOGRAPHY, "What ocean is on the West Coast of the United States?",
  ["Pacific (Ocean)"],
  "Đại Tây Dương Thái Bình Dương (Pacific Ocean) nằm dọc theo bờ biển phía Tây — nơi có các thành phố như Los Angeles, San Francisco, và Seattle.",
  "The Pacific Ocean borders the West Coast.",
  lessonId="lsn_088"),
q(90, GEOGRAPHY, "What ocean is on the East Coast of the United States?",
  ["Atlantic (Ocean)"],
  "Đại Tây Dương (Atlantic Ocean) nằm dọc theo bờ biển phía Đông — nơi có các thành phố như New York, Boston, và Miami.",
  "The Atlantic Ocean borders the East Coast.",
  lessonId="lsn_088"),
q(91, GEOGRAPHY, "Name one U.S. territory.",
  ["Puerto Rico", "U.S. Virgin Islands", "American Samoa", "Northern Mariana Islands", "Guam"],
  "Ngoài 50 tiểu bang, Mỹ còn có các lãnh thổ (territories) như Puerto Rico, Guam, và quần đảo Virgin thuộc Mỹ — người dân ở đây là công dân Mỹ nhưng không có Thượng nghị sĩ hay Dân biểu có quyền biểu quyết đầy đủ.",
  "U.S. territories include Puerto Rico, Guam, and the Virgin Islands."),
q(92, GEOGRAPHY, "Name one state that borders Canada.",
  ["Maine", "New Hampshire", "Vermont", "New York", "Pennsylvania", "Ohio", "Michigan", "Minnesota",
   "North Dakota", "Montana", "Idaho", "Washington", "Alaska"],
  "13 tiểu bang có chung biên giới với Canada, trải dài từ Alaska ở cực Tây Bắc cho đến Maine ở cực Đông Bắc. Đây là đường biên giới hòa bình dài nhất thế giới.",
  "13 states border Canada, from Alaska to Maine.",
  lessonId="lsn_092"),
q(93, GEOGRAPHY, "Name one state that borders Mexico.",
  ["California", "Arizona", "New Mexico", "Texas"],
  "Bốn tiểu bang có chung biên giới với Mexico: California, Arizona, New Mexico, và Texas — tất cả đều nằm ở miền Tây Nam nước Mỹ.",
  "California, Arizona, New Mexico, and Texas border Mexico.",
  lessonId="lsn_092"),
q(94, GEOGRAPHY, "What is the capital of the United States?",
  ["Washington, D.C."],
  "Thủ đô của nước Mỹ là Washington, D.C. — không thuộc tiểu bang nào cả, mà là một khu vực đặc biệt (District of Columbia) được lập ra riêng làm trung tâm chính phủ liên bang.",
  "Washington, D.C. is the U.S. capital.",
  lessonId="lsn_094"),
q(95, GEOGRAPHY, "Where is the Statue of Liberty?",
  ["New York (Harbor)", "Liberty Island", "New Jersey", "near New York City", "on the Hudson River"],
  "Tượng Nữ thần Tự do đứng trên đảo Liberty Island, trong cảng New York — món quà của Pháp tặng Mỹ năm 1886, biểu tượng chào đón hàng triệu người nhập cư khi họ đến Mỹ bằng đường biển.",
  "The Statue of Liberty stands in New York Harbor."),

q(96, SYMBOLS, "Why does the flag have 13 stripes?",
  ["because there were 13 original colonies", "because the stripes represent the original colonies"],
  "13 sọc trên lá cờ Mỹ tượng trưng cho 13 thuộc địa đầu tiên đã tuyên bố độc lập.",
  "The flag's 13 stripes represent the 13 original colonies.",
  lessonId="lsn_097"),
q(97, SYMBOLS, "Why does the flag have 50 stars?",
  ["because there is one star for each state", "because each star represents a state", "because there are 50 states"],
  "50 ngôi sao trên lá cờ đại diện cho 50 tiểu bang hiện nay của nước Mỹ — mỗi khi có tiểu bang mới gia nhập, một ngôi sao mới được thêm vào.",
  "The flag has one star for each of the 50 states.",
  lessonId="lsn_097"),
q(98, SYMBOLS, "What is the name of the national anthem?",
  ["The Star-Spangled Banner"],
  "Quốc ca Mỹ có tên \"The Star-Spangled Banner\" (Lá cờ lấp lánh ánh sao), được viết bởi Francis Scott Key năm 1814 khi ông chứng kiến lá cờ Mỹ vẫn tung bay sau một trận pháo kích ác liệt.",
  "The U.S. national anthem is \"The Star-Spangled Banner.\""),

q(99, HOLIDAYS, "When do we celebrate Independence Day?",
  ["July 4"],
  "Ngày lễ Độc lập được tổ chức vào ngày 4 tháng 7 hằng năm — kỷ niệm ngày bản Tuyên ngôn Độc lập được thông qua năm 1776.",
  "Independence Day is celebrated on July 4.",
  lessonId="lsn_063"),
q(100, HOLIDAYS, "Name two national U.S. holidays.",
  ["New Year's Day", "Martin Luther King, Jr. Day", "Presidents' Day", "Memorial Day", "Juneteenth",
   "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving", "Christmas"],
  "Nước Mỹ có nhiều ngày lễ liên bang trong năm, như Tết Dương lịch, ngày Lễ Lao động, Lễ Tạ ơn, và Giáng sinh. Bạn chỉ cần nhớ tên hai ngày lễ để trả lời đúng câu này.",
  "U.S. federal holidays include New Year's, Labor Day, and Thanksgiving.", requiredAnswerCount=2),
]

assert len(QUESTIONS) == 100, f"Expected 100 questions, got {len(QUESTIONS)}"
ids = sorted(item["id"] for item in QUESTIONS)
assert ids == list(range(1, 101)), "Question ids must be exactly 1..100"

CATEGORIES = [
    {"id": GOV_PRINCIPLES, "nameEN": "Principles of American Democracy", "nameVI": "Nguyên tắc Dân chủ Mỹ", "sfSymbol": "scroll", "sortOrder": 0},
    {"id": GOV_SYSTEM, "nameEN": "System of Government", "nameVI": "Hệ thống Chính quyền", "sfSymbol": "building.columns", "sortOrder": 1},
    {"id": GOV_RIGHTS, "nameEN": "Rights and Responsibilities", "nameVI": "Quyền và Trách nhiệm", "sfSymbol": "checkmark.shield", "sortOrder": 2},
    {"id": HIST_COLONIAL, "nameEN": "Colonial Period and Independence", "nameVI": "Thời kỳ Thuộc địa và Độc lập", "sfSymbol": "flag", "sortOrder": 3},
    {"id": HIST_1800S, "nameEN": "The 1800s", "nameVI": "Thế kỷ 19", "sfSymbol": "clock.arrow.circlepath", "sortOrder": 4},
    {"id": HIST_RECENT, "nameEN": "Recent American History", "nameVI": "Lịch sử Mỹ Hiện đại", "sfSymbol": "newspaper", "sortOrder": 5},
    {"id": GEOGRAPHY, "nameEN": "Geography", "nameVI": "Địa lý", "sfSymbol": "map", "sortOrder": 6},
    {"id": SYMBOLS, "nameEN": "Symbols", "nameVI": "Biểu tượng", "sfSymbol": "star.circle", "sortOrder": 7},
    {"id": HOLIDAYS, "nameEN": "Holidays", "nameVI": "Ngày lễ", "sfSymbol": "calendar", "sortOrder": 8},
]

# ---------------------------------------------------------------------------
# Flagship "rich narrative" lesson scripts (whiteboard-animation style)
# ---------------------------------------------------------------------------
def beat(id, en, vi, at, dur):
    return {"id": id, "textEN": en, "textVI": vi, "atSeconds": at, "durationSeconds": dur}

def action(id, type, at, dur, **kw):
    a = {"id": id, "type": type, "atSeconds": at, "durationSeconds": dur,
         "textEN": kw.get("textEN"), "textVI": kw.get("textVI"), "symbol": kw.get("symbol"),
         "region": kw.get("region"), "cityName": kw.get("cityName"), "year": kw.get("year"),
         "items": kw.get("items")}
    return a

def lesson(id, question_ids, titleEN, titleVI, category, narration, actions, video_file=None):
    """Every flagship lesson ships with a bundled video named after its id
    (see scripts/placeholder_videos/). Pass video_file=False for a lesson
    that should fall back to the procedural whiteboard renderer instead;
    videoURLString stays None until videos move to cloud hosting, at which
    point it takes priority over the bundled file."""
    total = max([n["atSeconds"] + n["durationSeconds"] for n in narration] +
                [a["atSeconds"] + a["durationSeconds"] for a in actions] + [0.0])
    if video_file is None:
        video_file = f"{id}.mp4"
    return {"id": id, "questionIds": question_ids, "titleEN": titleEN, "titleVI": titleVI,
            "category": category, "totalDurationSeconds": round(total, 1),
            "narration": narration, "actions": actions, "style": "richNarrative",
            "videoURLString": None, "videoFileName": video_file or None}

LESSONS = [
lesson("lsn_001", [1], "The Rulebook Above All Rules", "Cuốn Luật Đứng Trên Mọi Luật", GOV_PRINCIPLES,
  [beat("n1", "Imagine every law in America as a player in a giant game.", "Hãy tưởng tượng mọi đạo luật ở Mỹ như một người chơi trong một trò chơi khổng lồ.", 0, 5),
   beat("n2", "Every single player — federal, state, even the President — has to follow one rulebook.", "Mọi \"người chơi\" — luật liên bang, luật tiểu bang, thậm chí cả Tổng thống — đều phải tuân theo một cuốn luật duy nhất.", 5, 6),
   beat("n3", "That rulebook is the Constitution. It's the supreme law of the land.", "Cuốn luật đó chính là Hiến pháp. Đó là luật tối cao của cả đất nước.", 11, 5),
   beat("n4", "No law, no governor, no president can overrule it.", "Không một đạo luật, thống đốc, hay tổng thống nào có thể vượt qua nó.", 16, 5)],
  [action("a1", "titleCard", 0, 5, textEN="Who's the boss?", textVI="Ai là người đứng đầu?", symbol="scalemass"),
   action("a2", "comparisonCards", 5, 6, items=[
       {"textEN": "Federal laws", "textVI": "Luật liên bang"},
       {"textEN": "State laws", "textVI": "Luật tiểu bang"},
       {"textEN": "The President", "textVI": "Tổng thống"}]),
   action("a3", "documentReveal", 11, 5, textEN="The Constitution", textVI="Hiến Pháp", symbol="scroll"),
   action("a4", "bulletList", 16, 5, items=[{"textEN": "Supreme law of the land", "textVI": "Luật tối cao của đất nước"}])]),

lesson("lsn_006", [5, 6], "Five Freedoms, One Hand", "Năm Quyền Tự Do, Một Bàn Tay", GOV_PRINCIPLES,
  [beat("n1", "The first ten amendments are called the Bill of Rights.", "Mười tu chính án đầu tiên được gọi là Tuyên ngôn Nhân quyền.", 0, 5),
   beat("n2", "The very first one — the First Amendment — actually protects five freedoms at once.", "Tu chính án đầu tiên bảo vệ đến năm quyền tự do cùng một lúc.", 5, 5),
   beat("n3", "Think of one hand: speech, religion, press, assembly, and petition — five fingers, five freedoms.", "Hãy nghĩ đến một bàn tay: ngôn luận, tôn giáo, báo chí, hội họp, và kiến nghị — năm ngón tay, năm quyền tự do.", 10, 7)],
  [action("a1", "documentReveal", 0, 5, textEN="Bill of Rights", textVI="Tuyên Ngôn Nhân Quyền", symbol="doc.text"),
   action("a2", "titleCard", 5, 5, textEN="First Amendment", textVI="Tu Chính Án Thứ Nhất", symbol="1.circle"),
   action("a3", "bulletList", 10, 7, items=[
       {"textEN": "Speech", "textVI": "Ngôn luận"}, {"textEN": "Religion", "textVI": "Tôn giáo"},
       {"textEN": "Press", "textVI": "Báo chí"}, {"textEN": "Assembly", "textVI": "Hội họp"},
       {"textEN": "Petition", "textVI": "Kiến nghị"}])]),

lesson("lsn_013", [13, 14, 37], "Three Legs of One Stool", "Ba Chân Của Một Chiếc Ghế", GOV_SYSTEM,
  [beat("n1", "The U.S. government stands on three branches, like a stool with three legs.", "Chính phủ Mỹ đứng vững nhờ ba nhánh, giống như một chiếc ghế ba chân.", 0, 6),
   beat("n2", "Congress makes the laws. The President carries them out. The courts explain them.", "Quốc hội làm luật. Tổng thống thi hành luật. Tòa án giải thích luật.", 6, 7),
   beat("n3", "Each branch can check the others, so no single leg can grow too powerful and tip the stool over.", "Mỗi nhánh có thể kiểm soát các nhánh còn lại, để không một nhánh nào trở nên quá mạnh và làm lật đổ cả chiếc ghế.", 13, 7)],
  [action("a1", "titleCard", 0, 6, textEN="Three branches", textVI="Ba nhánh chính quyền", symbol="building.columns"),
   action("a2", "comparisonCards", 6, 7, items=[
       {"textEN": "Legislative — Congress makes laws", "textVI": "Lập pháp — Quốc hội làm luật"},
       {"textEN": "Executive — President enforces laws", "textVI": "Hành pháp — Tổng thống thi hành luật"},
       {"textEN": "Judicial — Courts interpret laws", "textVI": "Tư pháp — Tòa án giải thích luật"}]),
   action("a3", "bulletList", 13, 7, items=[{"textEN": "Checks and balances", "textVI": "Kiểm soát và cân bằng"}])]),

lesson("lsn_017", [17, 18, 19, 21, 22], "Two Houses, One Congress", "Hai Viện, Một Quốc Hội", GOV_SYSTEM,
  [beat("n1", "Congress has two houses under one roof: the Senate and the House of Representatives.", "Quốc hội có hai viện dưới một mái nhà: Thượng viện và Hạ viện.", 0, 6),
   beat("n2", "The Senate: 100 seats, exactly two per state, six-year terms.", "Thượng viện: 100 ghế, mỗi tiểu bang đúng hai ghế, nhiệm kỳ sáu năm.", 6, 6),
   beat("n3", "The House: 435 seats split up by each state's population, two-year terms.", "Hạ viện: 435 ghế chia theo dân số từng tiểu bang, nhiệm kỳ hai năm.", 12, 6),
   beat("n4", "Big states like California get more House seats. Every state gets the same two Senate seats.", "Tiểu bang đông dân như California có nhiều ghế Hạ viện hơn. Nhưng mọi tiểu bang đều có đúng hai ghế Thượng viện.", 18, 7)],
  [action("a1", "titleCard", 0, 6, textEN="U.S. Congress", textVI="Quốc Hội Hoa Kỳ", symbol="building.columns.fill"),
   action("a2", "comparisonCards", 6, 6, items=[{"textEN": "Senate: 100 seats, 2 per state, 6-year term", "textVI": "Thượng viện: 100 ghế, 2/tiểu bang, nhiệm kỳ 6 năm"}]),
   action("a3", "comparisonCards", 12, 6, items=[{"textEN": "House: 435 seats by population, 2-year term", "textVI": "Hạ viện: 435 ghế theo dân số, nhiệm kỳ 2 năm"}]),
   action("a4", "mapUSA", 18, 7),
   action("a5", "highlightRegion", 18, 7, region="west", textEN="More people = more seats", textVI="Đông dân hơn = nhiều ghế hơn")]),

lesson("lsn_021", [21, 25], "Why Some States Get More Votes", "Vì Sao Có Tiểu Bang Nhiều Ghế Hơn", GOV_SYSTEM,
  [beat("n1", "The House of Representatives has 435 seats total.", "Hạ viện có tổng cộng 435 ghế.", 0, 5),
   beat("n2", "Those seats aren't split evenly — they follow population.", "Những ghế này không chia đều — mà theo dân số.", 5, 5),
   beat("n3", "A crowded state like California gets many seats. A small state like Wyoming gets just one.", "Một tiểu bang đông dân như California có nhiều ghế. Một tiểu bang nhỏ như Wyoming chỉ có một ghế.", 10, 7)],
  [action("a1", "titleCard", 0, 5, textEN="435 seats", textVI="435 ghế", symbol="person.3.fill"),
   action("a2", "mapUSA", 5, 12),
   action("a3", "highlightRegion", 5, 6, region="west", textEN="California: many seats", textVI="California: nhiều ghế"),
   action("a4", "highlightRegion", 11, 6, region="midwest", textEN="Wyoming: 1 seat", textVI="Wyoming: 1 ghế")]),

lesson("lsn_058", [58], "Why They Came", "Vì Sao Họ Đến", HIST_COLONIAL,
  [beat("n1", "People crossed an ocean for many reasons: to worship freely, to escape persecution, to find opportunity.", "Người ta vượt đại dương vì nhiều lý do: để tự do thờ phượng, thoát khỏi sự đàn áp, tìm kiếm cơ hội mới.", 0, 8),
   beat("n2", "It's a story many Vietnamese families know well too — a hard journey toward a new beginning.", "Đây cũng là câu chuyện mà nhiều gia đình người Việt rất quen thuộc — một hành trình gian nan hướng tới một khởi đầu mới.", 8, 7)],
  [action("a1", "titleCard", 0, 8, textEN="Why did colonists come?", textVI="Vì sao người thuộc địa đến Mỹ?", symbol="sailboat"),
   action("a2", "bulletList", 8, 7, items=[
       {"textEN": "Religious freedom", "textVI": "Tự do tôn giáo"},
       {"textEN": "Escape persecution", "textVI": "Thoát khỏi đàn áp"},
       {"textEN": "Economic opportunity", "textVI": "Cơ hội kinh tế"}])]),

lesson("lsn_061", [61], "No Taxation Without Representation", "Không Đại Diện Thì Không Đóng Thuế", HIST_COLONIAL,
  [beat("n1", "Britain kept raising taxes on the colonists.", "Nước Anh liên tục tăng thuế đối với người thuộc địa.", 0, 5),
   beat("n2", "But the colonists had no voice, no vote, in the British Parliament that set those taxes.", "Nhưng người thuộc địa không có tiếng nói, không có lá phiếu, trong Nghị viện Anh — nơi đặt ra các mức thuế đó.", 5, 6),
   beat("n3", "\"No taxation without representation\" became their rallying cry — and one spark of the Revolution.", "\"Không đại diện thì không đóng thuế\" trở thành khẩu hiệu của họ — một trong những ngòi nổ của cuộc Cách mạng.", 11, 6)],
  [action("a1", "titleCard", 0, 5, textEN="Rising taxes", textVI="Thuế tăng cao", symbol="dollarsign.circle"),
   action("a2", "quote", 5, 6, textEN="No representation in Parliament", textVI="Không có đại diện trong Nghị viện"),
   action("a3", "quote", 11, 6, textEN="\"No taxation without representation\"", textVI="\"Không đại diện thì không đóng thuế\"")]),

lesson("lsn_063", [8, 62, 63, 99], "The Fourth of July", "Ngày Mùng Bốn Tháng Bảy", HIST_COLONIAL,
  [beat("n1", "Thomas Jefferson picked up his pen and wrote a bold declaration.", "Thomas Jefferson cầm bút viết nên một bản tuyên bố táo bạo.", 0, 6),
   beat("n2", "On July 4, 1776, it was adopted: the colonies announced they were free from Great Britain.", "Ngày 4 tháng 7 năm 1776, bản tuyên bố được thông qua: các thuộc địa tuyên bố họ được tự do khỏi nước Anh.", 6, 7),
   beat("n3", "That's why every July 4th, Americans watch fireworks light up the sky — it's Independence Day.", "Đó là lý do mỗi ngày 4 tháng 7, người Mỹ ngắm pháo hoa rực rỡ trên bầu trời — đó là ngày Lễ Độc lập.", 13, 6)],
  [action("a1", "documentReveal", 0, 6, textEN="Declaration of Independence", textVI="Tuyên Ngôn Độc Lập", symbol="pencil.and.scribble"),
   action("a2", "timeline", 6, 7, year=1776, textEN="July 4, 1776", textVI="4 tháng 7, 1776"),
   action("a3", "showIcon", 13, 6, symbol="sparkles", textEN="Independence Day", textVI="Ngày Lễ Độc Lập")]),

lesson("lsn_064", [64], "Thirteen Colonies on the Coast", "Mười Ba Thuộc Địa Ven Biển", HIST_COLONIAL,
  [beat("n1", "Before there were fifty states, there were just thirteen colonies.", "Trước khi có năm mươi tiểu bang, chỉ có mười ba thuộc địa.", 0, 5),
   beat("n2", "They formed a thin ribbon along the Atlantic coast — from New Hampshire in the north to Georgia in the south.", "Chúng tạo thành một dải đất hẹp dọc bờ biển Đại Tây Dương — từ New Hampshire ở phía Bắc đến Georgia ở phía Nam.", 5, 8),
   beat("n3", "Names like Virginia, Massachusetts, and Pennsylvania all started right here.", "Những cái tên như Virginia, Massachusetts, và Pennsylvania đều bắt đầu từ đây.", 13, 6)],
  [action("a1", "titleCard", 0, 5, textEN="13 original colonies", textVI="13 thuộc địa ban đầu", symbol="13.circle"),
   action("a2", "mapUSA", 5, 14),
   action("a3", "highlightRegion", 5, 14, region="northeast", textEN="The 13 colonies", textVI="13 thuộc địa"),
   action("a4", "dropPin", 13, 6, cityName="Virginia", region="northeast"),
   action("a5", "dropPin", 13, 6, cityName="Massachusetts", region="northeast"),
   action("a6", "dropPin", 13, 6, cityName="Pennsylvania", region="northeast")]),

lesson("lsn_066", [65, 66], "Philadelphia, Summer of 1787", "Philadelphia, Mùa Hè Năm 1787", HIST_COLONIAL,
  [beat("n1", "Eleven years after independence, the Founding Fathers gathered in Philadelphia.", "Mười một năm sau khi độc lập, các nhà lập quốc tụ họp tại Philadelphia.", 0, 6),
   beat("n2", "Their mission: write the rulebook for a brand-new government. The result was the Constitution.", "Nhiệm vụ của họ: viết ra cuốn luật cho một chính phủ hoàn toàn mới. Kết quả là bản Hiến pháp.", 6, 7)],
  [action("a1", "timeline", 0, 6, year=1787, textEN="Constitutional Convention", textVI="Hội Nghị Lập Hiến"),
   action("a2", "documentReveal", 6, 7, textEN="The Constitution", textVI="Hiến Pháp", symbol="building.columns")]),

lesson("lsn_073", [73, 74], "A Nation Divided", "Một Quốc Gia Chia Cắt", HIST_1800S,
  [beat("n1", "By the 1860s, the North and South disagreed bitterly over slavery.", "Đến những năm 1860, miền Bắc và miền Nam bất đồng sâu sắc về chế độ nô lệ.", 0, 6),
   beat("n2", "That disagreement, along with states' rights and economic differences, split the country in two.", "Bất đồng đó, cùng với vấn đề quyền tiểu bang và khác biệt kinh tế, đã chia đất nước làm đôi.", 6, 6),
   beat("n3", "The result was the Civil War — Americans fighting Americans.", "Kết quả là cuộc Nội chiến — người Mỹ chiến đấu chống lại người Mỹ.", 12, 5)],
  [action("a1", "mapUSA", 0, 6),
   action("a2", "highlightRegion", 0, 6, region="northeast", textEN="The North", textVI="Miền Bắc"),
   action("a3", "highlightRegion", 6, 6, region="southeast", textEN="The South", textVI="Miền Nam"),
   action("a4", "titleCard", 12, 5, textEN="The Civil War, 1861–1865", textVI="Nội Chiến, 1861–1865", symbol="flag.2.crossed")]),

lesson("lsn_075", [75, 76], "The President Who Freed a Nation", "Vị Tổng Thống Giải Phóng Cả Một Dân Tộc", HIST_1800S,
  [beat("n1", "Abraham Lincoln led the country through its darkest, bloodiest chapter.", "Abraham Lincoln dẫn dắt đất nước qua chương đen tối và đẫm máu nhất.", 0, 6),
   beat("n2", "In 1863, he signed the Emancipation Proclamation, declaring enslaved people in the Confederacy free.", "Năm 1863, ông ký Tuyên ngôn Giải phóng Nô lệ, tuyên bố những người nô lệ ở miền Nam ly khai được tự do.", 6, 7),
   beat("n3", "He preserved the Union and pushed the nation toward ending slavery for good.", "Ông giữ cho Liên bang không bị chia cắt và thúc đẩy đất nước tiến tới việc xóa bỏ hoàn toàn chế độ nô lệ.", 13, 6)],
  [action("a1", "titleCard", 0, 6, textEN="Abraham Lincoln", textVI="Abraham Lincoln", symbol="person.fill"),
   action("a2", "timeline", 6, 7, year=1863, textEN="Emancipation Proclamation", textVI="Tuyên Ngôn Giải Phóng Nô Lệ"),
   action("a3", "bulletList", 13, 6, items=[{"textEN": "Preserved the Union", "textVI": "Giữ gìn Liên bang"}])]),

lesson("lsn_088", [88, 89, 90], "Coast to Coast, River to River", "Từ Bờ Biển Này Sang Bờ Biển Kia", GEOGRAPHY,
  [beat("n1", "Picture the United States as one giant map stretching between two oceans.", "Hãy hình dung nước Mỹ như một tấm bản đồ khổng lồ trải dài giữa hai đại dương.", 0, 6),
   beat("n2", "On the west edge: the Pacific Ocean. On the east edge: the Atlantic Ocean.", "Ở rìa phía Tây: Thái Bình Dương. Ở rìa phía Đông: Đại Tây Dương.", 6, 6),
   beat("n3", "And running down the middle, like a spine, are the Mississippi and Missouri Rivers — the two longest in the country.", "Chạy dọc chính giữa, như một cột sống, là sông Mississippi và sông Missouri — hai con sông dài nhất đất nước.", 12, 7)],
  [action("a1", "mapUSA", 0, 19),
   action("a2", "highlightRegion", 6, 6, region="west", textEN="Pacific Ocean", textVI="Thái Bình Dương"),
   action("a3", "highlightRegion", 6, 6, region="northeast", textEN="Atlantic Ocean", textVI="Đại Tây Dương"),
   action("a4", "highlightRegion", 12, 7, region="midwest", textEN="Mississippi & Missouri Rivers", textVI="Sông Mississippi & Missouri")]),

lesson("lsn_092", [92, 93], "Neighbors North and South", "Láng Giềng Phía Bắc và Phía Nam", GEOGRAPHY,
  [beat("n1", "The United States has two neighboring countries.", "Nước Mỹ có hai quốc gia láng giềng.", 0, 4),
   beat("n2", "Up north, thirteen states share a border with Canada, from Alaska to Maine.", "Ở phía Bắc, mười ba tiểu bang có chung biên giới với Canada, từ Alaska đến Maine.", 4, 7),
   beat("n3", "Down south, four states — California, Arizona, New Mexico, and Texas — border Mexico.", "Ở phía Nam, bốn tiểu bang — California, Arizona, New Mexico, và Texas — có chung biên giới với Mexico.", 11, 7)],
  [action("a1", "mapUSA", 0, 18),
   action("a2", "highlightRegion", 4, 7, region="west", textEN="Borders Canada", textVI="Giáp Canada"),
   action("a3", "highlightRegion", 11, 7, region="southwest", textEN="Borders Mexico", textVI="Giáp Mexico")]),

lesson("lsn_094", [94], "A Capital Built for Government", "Thủ Đô Được Xây Riêng Cho Chính Quyền", GEOGRAPHY,
  [beat("n1", "Unlike most capitals, Washington, D.C. isn't inside any state.", "Khác với hầu hết các thủ đô, Washington, D.C. không thuộc tiểu bang nào cả.", 0, 6),
   beat("n2", "It's its own special federal district, built specifically to be the seat of the national government.", "Đó là một đặc khu liên bang riêng, được xây dựng chuyên để làm trung tâm của chính phủ quốc gia.", 6, 7)],
  [action("a1", "mapUSA", 0, 13),
   action("a2", "dropPin", 6, 7, cityName="Washington, D.C.", region="northeast")]),

lesson("lsn_097", [96, 97], "Fifty Stars, Thirteen Stripes", "Năm Mươi Ngôi Sao, Mười Ba Sọc", SYMBOLS,
  [beat("n1", "Look closely at the American flag and you'll find a whole history lesson.", "Nhìn kỹ lá cờ Mỹ, bạn sẽ thấy cả một bài học lịch sử.", 0, 5),
   beat("n2", "Thirteen stripes for the thirteen original colonies that declared independence together.", "Mười ba sọc tượng trưng cho mười ba thuộc địa ban đầu đã cùng nhau tuyên bố độc lập.", 5, 6),
   beat("n3", "And fifty stars — one for every state in the country today, from the Northeast all the way to the West Coast.", "Và năm mươi ngôi sao — mỗi ngôi sao đại diện cho một tiểu bang hiện nay, từ vùng Đông Bắc trải dài đến bờ Tây.", 11, 7),
   beat("n4", "Next time you see the flag, you're really looking at a map of the whole country.", "Lần tới khi nhìn thấy lá cờ, thực ra bạn đang nhìn thấy cả một tấm bản đồ đất nước.", 18, 6)],
  [action("a1", "flagReveal", 0, 5),
   action("a2", "bulletList", 5, 6, items=[{"textEN": "13 stripes = 13 original colonies", "textVI": "13 sọc = 13 thuộc địa ban đầu"}]),
   action("a3", "mapUSA", 11, 13),
   action("a4", "highlightRegion", 11, 3, region="northeast", textEN="50 states", textVI="50 tiểu bang"),
   action("a5", "highlightRegion", 14, 3, region="southeast", textEN="50 states", textVI="50 tiểu bang"),
   action("a6", "highlightRegion", 17, 3, region="midwest", textEN="50 states", textVI="50 tiểu bang"),
   action("a7", "highlightRegion", 18, 3, region="west", textEN="50 states", textVI="50 tiểu bang")]),
]

lesson_ids = {l["id"] for l in LESSONS}
for lscript in LESSONS:
    for qid in lscript["questionIds"]:
        assert 1 <= qid <= 100

# ---------------------------------------------------------------------------
# Static state capitals (does not change over time — safe to bundle)
# ---------------------------------------------------------------------------
STATE_CAPITALS = {
    "Alabama": "Montgomery", "Alaska": "Juneau", "Arizona": "Phoenix", "Arkansas": "Little Rock",
    "California": "Sacramento", "Colorado": "Denver", "Connecticut": "Hartford", "Delaware": "Dover",
    "Florida": "Tallahassee", "Georgia": "Atlanta", "Hawaii": "Honolulu", "Idaho": "Boise",
    "Illinois": "Springfield", "Indiana": "Indianapolis", "Iowa": "Des Moines", "Kansas": "Topeka",
    "Kentucky": "Frankfort", "Louisiana": "Baton Rouge", "Maine": "Augusta", "Maryland": "Annapolis",
    "Massachusetts": "Boston", "Michigan": "Lansing", "Minnesota": "Saint Paul", "Mississippi": "Jackson",
    "Missouri": "Jefferson City", "Montana": "Helena", "Nebraska": "Lincoln", "Nevada": "Carson City",
    "New Hampshire": "Concord", "New Jersey": "Trenton", "New Mexico": "Santa Fe", "New York": "Albany",
    "North Carolina": "Raleigh", "North Dakota": "Bismarck", "Ohio": "Columbus", "Oklahoma": "Oklahoma City",
    "Oregon": "Salem", "Pennsylvania": "Harrisburg", "Rhode Island": "Providence", "South Carolina": "Columbia",
    "South Dakota": "Pierre", "Tennessee": "Nashville", "Texas": "Austin", "Utah": "Salt Lake City",
    "Vermont": "Montpelier", "Virginia": "Richmond", "Washington": "Olympia", "West Virginia": "Charleston",
    "Wisconsin": "Madison", "Wyoming": "Cheyenne",
}

# ---------------------------------------------------------------------------
# Current officials — deliberately placeholders; update before each release.
# ---------------------------------------------------------------------------
CURRENT_OFFICIALS = {
    "lastUpdated": "2026-01-01",
    "needsReviewAfterDays": 90,
    "president": "Update in Settings > Content Admin before release",
    "vicePresident": "Update in Settings > Content Admin before release",
    "speakerOfHouse": "Update in Settings > Content Admin before release",
    "chiefJustice": "Update in Settings > Content Admin before release",
    "presidentParty": "Update in Settings > Content Admin before release",
    "sourceNote": "Verify against uscis.gov and house.gov/senate.gov before shipping. This file ships as bundled JSON so it can be swapped without a code change.",
}

# ---------------------------------------------------------------------------
# Tutor character dialogue
# ---------------------------------------------------------------------------
CHARACTER = {
    "id": "lien",
    "nameEN": "Ms. Lien",
    "nameVI": "Chị Liên",
    "bioEN": "A warm, patient guide who studied for her own citizenship test and remembers exactly how it feels.",
    "bioVI": "Một người hướng dẫn ấm áp, kiên nhẫn — từng tự mình ôn thi quốc tịch nên rất hiểu cảm giác của bạn.",
    "greetings": [
        {"textEN": "Welcome back! Ready for today's five minutes?", "textVI": "Chào mừng bạn quay lại! Sẵn sàng cho năm phút hôm nay chưa?"},
        {"textEN": "Hi there! Let's pick up right where we left off.", "textVI": "Chào bạn! Mình tiếp tục từ chỗ đã dừng nhé."},
        {"textEN": "Good to see you again. Small steps every day add up.", "textVI": "Rất vui được gặp lại bạn. Mỗi ngày một chút, rồi sẽ thành công."}
    ],
    "correctAnswer": [
        {"textEN": "That's right! You've got it.", "textVI": "Chính xác! Bạn làm được rồi."},
        {"textEN": "Correct — nicely done.", "textVI": "Đúng rồi — làm tốt lắm."},
        {"textEN": "Yes! You're remembering this well.", "textVI": "Đúng vậy! Bạn nhớ bài rất tốt."}
    ],
    "incorrectAnswer": [
        {"textEN": "Not quite — let's look at it again together.", "textVI": "Chưa đúng — mình cùng xem lại nhé."},
        {"textEN": "Close, but not the answer USCIS is looking for. One more look.", "textVI": "Gần đúng rồi, nhưng chưa phải câu trả lời USCIS cần. Xem lại một chút nhé."},
        {"textEN": "That's okay — mistakes are how this sticks in memory.", "textVI": "Không sao cả — sai rồi mới nhớ lâu."}
    ],
    "streakEncouragement": [
        {"textEN": "Look at that streak! You're building a real habit.", "textVI": "Nhìn chuỗi ngày học kìa! Bạn đang xây một thói quen thật sự."},
        {"textEN": "Every day you show up, this gets easier.", "textVI": "Mỗi ngày bạn kiên trì, việc này sẽ càng dễ hơn."}
    ],
    "sessionComplete": [
        {"textEN": "That's a wrap for today. See you tomorrow!", "textVI": "Vậy là xong bài hôm nay. Hẹn gặp lại ngày mai!"},
        {"textEN": "Great session. Your future interview officer won't stand a chance.", "textVI": "Buổi học rất tốt. Viên chức phỏng vấn sau này sẽ không làm khó được bạn đâu."}
    ],
}

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
os.makedirs(OUT_DIR, exist_ok=True)

def write_json(name, data):
    path = os.path.join(OUT_DIR, name)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"wrote {path} ({len(json.dumps(data))} bytes)")

write_json("civics_questions.json", QUESTIONS)
write_json("categories.json", CATEGORIES)
write_json("lessons.json", LESSONS)
write_json("state_capitals.json", STATE_CAPITALS)
write_json("current_officials.json", CURRENT_OFFICIALS)
write_json("character.json", CHARACTER)

print("\nDone. 100 questions, {} flagship lessons, {} categories.".format(len(LESSONS), len(CATEGORIES)))
